### PR TITLE
Backup user registration information

### PR DESCRIPTION
**Pull request by hugares**
Add a backup schedule for the toolchain operators, both host and member.

[RHTAPSRE-285](https://issues.redhat.com//browse/RHTAPSRE-285)

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]
LGTM

**Comment by hugares** [comment]
> LGTM

@alexeykazakov looks like this command does not work, lgtm label was not applied. Can you comment "/lgtm"?

**Comment by alexeykazakov** [comment]
It was not my intent to merge this PR this is why I didn't use `/lgtm` comment :) I wanted someone from the RHTAP infra team to approve/get merged. But please let me know if you still want me to `/lgtm` this PR.

**Comment by hugares** [comment]
> It was not my intent to merge this PR this is why I didn't use `/lgtm` comment :) I wanted someone from the RHTAP infra team to approve/get merged. But please let me know if you still want me to `/lgtm` this PR.

Thanks, let's wait for a review from someone in infra team.

**Review by manish-jangra — APPROVED** [review]
looks good

**Review by amfred — APPROVED** [review]

**Pull request merged**
