### PR TITLE
pipeline-service update dev/staging through mv back pac back to upstream

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
whew .... clean main e2e at https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1860/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1662128347603275776 @Roming22 :-)

**Comment by gabemontero** [comment]
the hac error was a pre test gcr.io flake

**Comment by gabemontero** [comment]
That is 2 passing appstudio-e2e-tests:

```
 INFO[2023-05-26T18:55:28Z] Step appstudio-e2e-tests-redhat-appstudio-e2e succeeded after 39m45s. 
INFO[2023-05-26T18:55:28Z] Step phase test succeeded after 39m45s.      
```

**Comment by gabemontero** [comment]
ok no need for rebase / have labels / fingers crossed on e2e's

**Pull request merged**
