### PR TITLE
Promote release-service from development to staging

### PR DESCRIPTION
**Pull request by scoheb**
Included PRs:
 - https://github.com/redhat-appstudio/release-service/pull/299
 - https://github.com/redhat-appstudio/release-service/pull/302
 - https://github.com/redhat-appstudio/release-service/pull/296
 - https://github.com/redhat-appstudio/release-service/pull/292

### CODE REVIEW

**Review by happybhati — APPROVED** [review]

**Comment by flacatus** [comment]
@scoheb https://status.quay.io/

**Pull request merged**
