### PR TITLE
[DEVHAS-217] create an empty gitops-repo-pruner component

### PR DESCRIPTION
**Pull request by kim-tsao**
Signed-off-by: Kim Tsao <ktsao@redhat.com>

Creating an empty component so we can add the tekton files to our repo.  Once we are ready to deploy the repo, we will add the necessary resources

### CODE REVIEW

**Comment by sbose78** [comment]
Let us know once you have a team member 👍 'ing this PR :)

**Review by johnmcollier — APPROVED** [review]
/lgtm
/approve

**Comment by kim-tsao** [comment]
> Let us know once you have a team member 👍 'ing this PR :)

@sbose78, just got the approval

**Pull request merged**
