### PR TITLE
fix pipeline service team rbac for sprayproxy namespace

### PR DESCRIPTION
**Pull request by gabemontero**
As I hinted at in https://github.com/redhat-appstudio/infra-deployments/pull/1788#issue-1700406229 giving the pipeline service core pillar members view access to the sprayproxy namespace did not work when putting the yaml in the base dir

I've logged onto both staging and cluster (using some temporary permissions from Ann Marie) and can see the new RoleBinding is missing.

Explicitly defining in both staging and prod

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
cluster install fails ... need another rebase

**Comment by gabemontero** [comment]
per https://redhat-internal.slack.com/archives/C032EJ007C0/p1684253070621799 and communication with @sbose78 @Roming22 we will merge this even in summit/freeze mode given this does not change runtime behavior at all, but helps the team debug/triage

**Pull request merged**
