### PR TITLE
Update application service image reference

### PR DESCRIPTION
**Pull request by mmorhun**
Signed-off-by: Mykola Morhun <mmorhun@redhat.com>
Update reference to application service image according to changes in https://github.com/redhat-appstudio/application-service/pull/67

### CODE REVIEW

**Comment by Michkov** [comment]
Probably we should merge https://github.com/redhat-appstudio/infra-deployments/pull/169 first, since it's updating the global build-bundle setting.

**Comment by sbose78** [comment]
part of https://github.com/redhat-appstudio/infra-deployments/pull/176

**Pull request closed without merging**
