### PR TITLE
[DNM] Test OSP 1.12 upgrade

### PR DESCRIPTION
**Pull request by Roming22**

### CODE REVIEW

**Comment by gabemontero** [comment]
only 1 e2e-tests failure, but a chains one:

```
 Summarizing 1 Failure:
  [FAIL] [chains-suite Tekton Chains E2E tests] test creating and signing an image and task verify-enterprise-contract task [It] succeeds when policy is met [ec, HACBS, pipeline]
  /tmp/tmp.0b7HYAykXv/tests/build/chains.go:225
```

let's see how persistent that is, and if it is persistent, then we may have to dig into how the deployment of chains in 1.12 is affecting things here

**Comment by gabemontero** [comment]
per https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/2507/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1709579474581852160/artifacts/appstudio-e2e-tests/redhat-appstudio-gather/artifacts/must-gather-appstudio/quay-io-openshift-release-dev-ocp-v4-0-art-dev-sha256-8af2c323e4325849f71649bc0e6e140806e5196e5c2a6926aea1e0e0e4f10d8e/cluster-scoped-resources/operators.coreos.com/operators/openshift-pipelines-operator-rh.openshift-operators.yaml confirmed this was using 1.12

**Comment by gabemontero** [comment]
Same error again @Roming22 
```
 Summarizing 1 Failure:
  [FAIL] [chains-suite Tekton Chains E2E tests] test creating and signing an image and task verify-enterprise-contract task [It] succeeds when policy is met [ec, HACBS, pipeline]
  /tmp/tmp.X5C0t7OILc/tests/build/chains.go:225
```

I think we have to assume that 1.12 changed something wrt chains that is affecting the e2e's.  My PR https://github.com/redhat-appstudio/infra-deployments/pull/2508 should be a good sanity check to make sure this test is not flaking in general.

**Comment by gabemontero** [comment]
and again
```
 Summarizing 1 Failure:
  [FAIL] [chains-suite Tekton Chains E2E tests] test creating and signing an image and task verify-enterprise-contract task [It] succeeds when policy is met [ec, HACBS, pipeline]
  /tmp/tmp.ond9F4dCOQ/tests/build/chains.go:225
```

**Comment by Roming22** [comment]
All tests are successful. Closing the PR.

**Pull request closed without merging**
