### PR TITLE
SPI OAuth service update v0.5.5

### PR DESCRIPTION
**Pull request by skabashnyuk**
Add session cookie configuration SameSite=None and Secure=true 
  https://github.com/redhat-appstudio/service-provider-integration-oauth/pull/92
Context https://issues.redhat.com/projects/SVPI/issues/SVPI-113 [HAC-dev] no active oauth flow found for the state key

### CODE REVIEW

**Review by metlos — APPROVED** [review]

**Review by sparkoo — APPROVED** [review]
/lgtm

**Pull request merged**
