### PR TITLE
PVCORE-4433 - Add Power Monitoring Operator

### PR DESCRIPTION
**Pull request by raks-tt**
Add kepler and power-monitoring component

Add the power-monitoring application set to all cluster

### CODE REVIEW

**Comment by raks-tt** [comment]
@mftb @hugares - Please review

**Comment by hugares** [comment]
> The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://github.com/orgs/redhat-appstudio/people) of the redhat-appstudio org. You can then trigger verification by writing `/verify-owners` in a comment.
> 
> * mikebonnet
>   
>   * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.

I invited @mikebonnet to the org, once he accept the invite this check should pass

**Comment by mikebonnet** [comment]
> > The following users are mentioned in OWNERS file(s) but are untrusted for the following reasons. One way to make the user trusted is to add them as [members](https://github.com/orgs/redhat-appstudio/people) of the redhat-appstudio org. You can then trigger verification by writing `/verify-owners` in a comment.
> > 
> > * mikebonnet
> >   
> >   * User is not a member of the org. User is not a collaborator. Satisfy at least one of these conditions to make the user trusted.
> 
> I invited @mikebonnet to the org, once he accept the invite this check should pass

Just accepted the invite. Thanks!

**Review by hugares — APPROVED** [review]
/lgtm

**Comment by hugares** [comment]
@raks-tt Change is being deployed to all clusters, there is a permission issue to create kepler CR, I am working on fixing this

**Comment by hugares** [comment]
> @raks-tt Change is being deployed to all clusters, there is a permission issue to create kepler CR, I am working on fixing this

Done, power monitoring should be able to deploy to all clusters now

**Pull request merged**
