### PR TITLE
chore: move ci-helper-app Repo CR to konflux-ci

### PR DESCRIPTION
**Pull request by psturc**
[KONFLUX-2245](https://issues.redhat.com//browse/KONFLUX-2245)

### CODE REVIEW

**Comment by psturc** [comment]
@ralphbean is there a plan to store anything related to dev environment in `components/konflux-ci`?

I'm wondering if we should turn off triggering openshift-ci e2e jobs for changes made only in `components/konflux-ci` directory (i.e. to update [this regexp](https://github.com/openshift/release/blob/335c62472139fdd498e55afc773eced3fb4b8bc4/ci-operator/config/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main.yaml#L51))

**Comment by ralphbean** [comment]
@psturc good catch. No further plans for components/konflux-ci. I think it can be safely added to that regex.

**Pull request merged**
