### PR TITLE
update the image tag of release-service to be same as in main branch

### PR DESCRIPTION
**Pull request by kasemAlem**

### CODE REVIEW

**Comment by johnbieren** [comment]
This is not actually the commit of the main branch in release-service, and if it was, it would be a dupe of this automatically created pr https://github.com/redhat-appstudio/infra-deployments/pull/872

**Comment by kasemAlem** [comment]
> This is not actually the commit of the main branch in release-service, and if it was, it would be a dupe of this automatically created pr #872

I've changed the image to be as latest of release-service main branch, 
it's not a duplication of 872, this one is for pre-kcp branch

**Review by davidmogar — APPROVED** [review]

**Review by Michkov — CHANGES_REQUESTED** [review]
Only critical fixes should be accepted in pre-kcp branch, please provide justification.

**Comment by kasemAlem** [comment]
> Only critical fixes should be accepted in pre-kcp branch, please provide justification.

@Michkov, Basically this fix is about updating the image of release-service, which contains bug fixes 
in [PR](https://github.com/redhat-appstudio/e2e-tests/pull/223) if failing due to the bug been fixed with latest release-service

**Comment by kasemAlem** [comment]
Will merge the PR of release-e2e tests to the main branch

**Pull request closed without merging**
