### PR TITLE
Update pipeline-service

### PR DESCRIPTION
**Pull request by Roming22**
Update from e27e5385d26bcedf1aac52191b34ff020c30f6a2 to 3cce2e2dc3a468dfc1cde5a04c2a55583d9d1c66

Signed-off-by: Romain Arnaud <rarnaud@redhat.com>

### CODE REVIEW

**Comment by Roming22** [comment]
This change will bring in the fastest pruning frequency for pipelineruns.

**Comment by Dannyb48** [comment]
/retest 

Another instance of unstable Quay.io again. Failure aligns with https://issues.redhat.com/browse/SRVKP-2749

**Pull request merged**
