### PR TITLE
feat: Add service account for perf team to read from Prometheus

### PR DESCRIPTION
**Pull request by jhutar**
This was requested in https://issues.redhat.com/browse/RHTAPWATCH-388

### CODE REVIEW

**Comment by yftacherzog** [comment]
@jhutar does it work for you in dev?

**Comment by jhutar** [comment]
Hello @yftacherzog ! Just tested and looks OK:

```
$ oc whoami --show-context
default/api-rhosd-12-hacbs-ccitredhat-com:6443/kube:admin
$ HOST=$( oc -n openshift-monitoring get route -l app.kubernetes.io/name=thanos-query -o json | jq --raw-output '.items[0].spec.host' )
$ TOKEN=$( oc -n perf-team-prometheus-reader get secret/perf-team-prometheus-reader-cluster-sa-token-87npn -o json | jq --raw-output '.data.token | @base64d' )
$ status_data.py --additional ../mystoneinst/cluster_read_config.yaml --monitoring-start 2023-09-21T07:00:00+00:00 --monitoring-end 2023-09-21T07:15:00+00:00 --prometheus-host https://$HOST --prometheus-port 443 --prometheus-token $TOKEN
Gathered 12 `ok` data points. Not gathered 0 `bad` data points
```

**Review by yftacherzog — APPROVED** [review]

**Comment by amisstea** [comment]
@skabashnyuk can you PTAL? You're one of the only reviewers  in the OWNERS file.

**Review by amfred — APPROVED** [review]

**Pull request merged**
