### PR TITLE
Bump pipeline-service version

### PR DESCRIPTION
**Pull request by enarha**
Update pipeline-service to include Tekton Results change enabling gRPC access logging.

### CODE REVIEW

**Review by adambkaplan — COMMENTED** [review]
@enarha We should probably include c145a6af3eac31e267846450edc97c8553a04b83 as well (this drops the RBAC patch that is now included upstream.

**Comment by adambkaplan** [comment]
Full set of changes: https://github.com/openshift-pipelines/pipeline-service/compare/8f3ebf86101a4cf21fe7e86335e85a3fb6e3671f...0fb095cf1a346033746f8daaa29d275fe0c2a7a8

**Comment by enarha** [comment]
Updated.

**Review by adambkaplan — APPROVED** [review]
/approve

/lgtm

**Review by Roming22 — APPROVED** [review]

**Comment by enarha** [comment]
Rebased main on my feature branch.

**Comment by enarha** [comment]
@adambkaplan @Roming22 Can we get this one merge please.

**Comment by adambkaplan** [comment]
/retest

We had a least one test fail due a a quay.io issue:

```
error pushing image "quay.io/redhat-appstudio-qe/test-images:build-cd3c1-1680532902" to "docker://quay.io/redhat-appstudio-qe/test-images:build-cd3c1-1680532902": trying to reuse blob sha256:7cda6ce113beb1259d6bfcc07aec67b8bfe7bde8dba632c478befb5ff9c3f49a at destination: failed to read from destination repository redhat-appstudio-qe/test-images: 502 (Bad Gateway)
```

**Pull request merged**
