### PR TITLE
fix(KONFLUX-5949): add Snapshot permissions for maintainers

### PR DESCRIPTION
**Pull request by dirgim**
* Add create/update/patch permissions for the Snapshot resources to the Konflux maintainer role
* This will allow maintainers to [rerun integration tests](https://konflux-ci.dev/docs/how-tos/testing/integration/rerunning/) and [create manual or override Snapshots](https://konflux-ci.dev/docs/how-tos/testing/integration/override-snapshots/)

Signed-off-by: dirgim <kpavic@redhat.com>

### CODE REVIEW

**Comment by hugares** [comment]
@dirgim 2 comments:

1. Do not forget to update the permission ADR: https://github.com/konflux-ci/architecture/blob/main/ADR/0011-roles-and-permissions.md
2. Tiers must be regenerated once src folder is modified and included in this PR, follow instructions here: https://github.com/redhat-appstudio/infra-deployments/blob/main/components/sandbox/tiers/README.adoc

**Review by arewm — COMMENTED** [review]
Seems reasonable. I'll defer PR approval to infra as it seems like more needs to be done related to this

**Comment by dirgim** [comment]
@hugares thanks for the help on this, I've made the following updates:

- Opened https://github.com/konflux-ci/architecture/pull/221 with the ADR updates, feel free to check if the format is correct.
- I've (hopefully correctly) regenerated the nstemplate tiers

**Review by hugares — APPROVED** [review]
/lgtm

**Comment by hugares** [comment]
@dirgim, I forgot to comment about this: https://github.com/redhat-appstudio/infra-deployments/pull/5138

**Pull request merged**
