### PR TITLE
Update Openshift pipelines to v1.8

### PR DESCRIPTION
**Pull request by Michkov**
Testing PR for now to see which services are broken.

### CODE REVIEW

**Comment by psturc** [comment]
```
  Unexpected error:
      <*errors.errorString | 0xc001cab0f0>: {
          s: "error listing pipelineruns in build-e2e-dajw namespace",
      }
      error listing pipelineruns in build-e2e-dajw namespace
  occurred
  In [It] at: /tmp/tmp.8KuE447cPO/tests/build/build.go:169
```
ok I've seen this issue before when trying to run e2e against appstudio on kcp 🥲 it's caused by an [old version of tektoncd/pipeline client in e2e-tests](https://github.com/redhat-appstudio/e2e-tests/blob/efe154578d328c6a6ae8ba373a8506e472ecb904/go.mod#L31)

**Comment by psturc** [comment]
👀 
```
I1124 10:38:03.780230    5675 magefile.go:237] cannot determine e2e-tests Github branches for author Michkov: json: cannot unmarshal array into Go value of type main.GithubBranches. will stick with the redhat-appstudio/e2e-tests main branch for running testss
```

**Review by bnallapeta — APPROVED** [review]
/approve

**Review by psturc — APPROVED** [review]

**Pull request merged**
