### PR TITLE
Fix olm-restart kube-linter issues

### PR DESCRIPTION
**Pull request by hugares**
* set cpu/memory requests/limits
* run container with read only file system
* run container as non root user
* Change image as using latest tag is prohibited and image used only had latest tag

### CODE REVIEW

**Review by amfred — APPROVED** [review]
Please make sure this feedback gets to the Sandbox team as well.

**Comment by hugares** [comment]
@xcoulon @amfred Can you re-apply lgtm label

**Review by amfred — APPROVED** [review]

**Pull request merged**
