### PR TITLE
Bump prod pipeline service level to stage level

### PR DESCRIPTION
**Pull request by enarha**

### CODE REVIEW

**Comment by gabemontero** [comment]
see https://github.com/redhat-appstudio/infra-deployments/pull/3728 for the details of the recent bump to stage

**Comment by gabemontero** [comment]
/hold 

@enarha will cancel this hold during his Monday morning, May 27.

**Review by gabemontero — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
green `appstudio-e2e-tests` @enarha

**Comment by gabemontero** [comment]
on both the upgrade and hac failures the default project did not come up during appstudio bootstrap ...unrelated to tekton

/retest

**Comment by enarha** [comment]
All green. I'll remove the hold label on Monday.

**Pull request merged**
