### PR TITLE
chore(RHTAPWATCH-331): Add namespace to dummy service monitor example

### PR DESCRIPTION
**Pull request by Kousalya1998**
* Add a new yaml file that deploys the namespace
* Rename the namespace inside that new yaml files to 'dummy-service'
* Reference the namespace yaml file inside the kustomization yaml file

### CODE REVIEW

**Comment by yftacherzog** [comment]
@Kousalya1998 were you able to deploy it and test it in dev?

**Comment by Kousalya1998** [comment]
> @Kousalya1998 were you able to deploy it and test it in dev?

I haven't deployed or tested it yet. While I test this PR, I'll make it a draft

**Review by amisstea — APPROVED** [review]

**Review by hmariset — APPROVED** [review]
lgtm

**Review by avi-biton — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
