### PR TITLE
bump pipeline-service version

### PR DESCRIPTION
**Pull request by ramessesii2**
bump pipeline-service version
    - enable resolvers in openshift-pipelines
    - upgrade PAC to v0.17.0

### CODE REVIEW

**Comment by ramessesii2** [comment]
From the CI logs, Pipeline-service seems green with `pipeline-service-in-cluster-local       Synced   Progressing` with error in Build Service

**Comment by Michkov** [comment]
E2E-test-run: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1478/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1634125969281257472

Repository CRs created but no pipelineruns -> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1478/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1634125969281257472/artifacts/appstudio-e2e-tests/redhat-appstudio-gather/artifacts/repositories.json 

Pac watcher is faliing on `failed to list *v1.PipelineRun: the server could not find the requested resource (get pipelineruns.tekton.dev)` - https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1478/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1634125969281257472/artifacts/appstudio-e2e-tests/redhat-appstudio-hypershift-gather/artifacts/pods/pipelines-as-code_pipelines-as-code-watcher-55d8d87c48-4r5tf_pac-watcher.log

Pac controller is failing on `the server could not find the requested resource (post pipelineruns.tekton.dev)` -> https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1478/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1634125969281257472/artifacts/appstudio-e2e-tests/redhat-appstudio-hypershift-gather/artifacts/pods/pipelines-as-code_pipelines-as-code-controller-5554965d9c-qxmc4_pac-controller.log

**Comment by ramessesii2** [comment]
Closing this PR since it aims to ship PAC v0.17 with OSP-1.9. PAC-team has pointed out that we can't ship PAC v0.17.0 with OSP-1.9. The reason being PACv0.17 generates v1 PipelineRun on the cluster but 1.9 doesn't have v1 APIs. So, we'll have to wait for OSP-1.10 I believe to be able to upgrade PAC to v0.17 and greater.

**Pull request closed without merging**
