### PR TITLE
MintMaker: enable git-submodules manager

### PR DESCRIPTION
**Pull request by nvtnlucie**
Adds git-submodules manager for Renovate

### CODE REVIEW

**Comment by nvtnlucie** [comment]
@gnaponie @qixiang @staticf0x PTAL

**Comment by gnaponie** [comment]
Hey Lucie, thanks for the PR. Did you perform some sort of local testing?

**Comment by staticf0x** [comment]
git-submodules might require explicit enabling through https://docs.renovatebot.com/modules/manager/git-submodules/#enabling

Once it's enabled it also needs to be added to the docs: https://github.com/redhat-exd-rebuilds/mintmaker-docs/blob/main/src/user/managers.md

**Comment by nvtnlucie** [comment]
Thank you for the points, I have performed local testing on my forks on Gitlab and Renovate is now correctly spawning MRs for updated commits. I also created the link in docs ( https://github.com/redhat-exd-rebuilds/mintmaker-docs/pull/3 ). Can you take another look?

**Comment by gnaponie** [comment]
Nice job :)

**Pull request merged**
