### PR TITLE
promote hac-dev latest changes

### PR DESCRIPTION
**Pull request by sahil143**

### CODE REVIEW

**Comment by arewm** [comment]
This bring the HAC version up to what it is in the external production cluster. It includes one reverted commit from the current state.

/lgtm

**Comment by hugares** [comment]
One day I would like to understand where this "Red Hat Konflux" check is coming from...

**Comment by hugares** [comment]
> One day I would like to understand where this "Red Hat Konflux" check is coming from...

I amended the PR to get rid of that pending check...

**Review by hugares — APPROVED** [review]
/lgtm

**Pull request merged**
