### PR TITLE
SRVKP-5855: move all tekton related config to infra-deployments

### PR DESCRIPTION
**Pull request by gabemontero**
@enarha @savitaashture PTAL

In addition to bringing up the dev overlay via a konflux bootstrap, I ran these command to confirm the staging and production overlay deploy.yaml's are not as expected affected by this change, as the end result is suppose to be not changing actually values, just removing the use of the pipeline service overlay.

```
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments/components/pipeline-service/production  (mv-plnsrvce-to-infra)$ ../../../hack/generate-deploy-config.sh 
./stone-prd-m01/resources: ./stone-prd-m01/deploy.yaml
./stone-prd-rh01/resources: ./stone-prd-rh01/deploy.yaml
./stone-prod-p01/resources: ./stone-prod-p01/deploy.yaml
./stone-prod-p02/resources: ./stone-prod-p02/deploy.yaml
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments/components/pipeline-service/production  (mv-plnsrvce-to-infra)$ git status 
On branch mv-plnsrvce-to-infra
nothing to commit, working tree clean
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments/components/pipeline-service/production  (mv-plnsrvce-to-infra)$ cd ../staging/
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments/components/pipeline-service/staging  (mv-plnsrvce-to-infra)$ git status 
On branch mv-plnsrvce-to-infra
nothing to commit, working tree clean
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments/components/pipeline-service/staging  (mv-plnsrvce-to-infra)$ ../../../hack/generate-deploy-config.sh 
./stone-stg-m01/resources: ./stone-stg-m01/deploy.yaml
./stone-stg-rh01/resources: ./stone-stg-rh01/deploy.yaml
./stone-stage-p01/resources: ./stone-stage-p01/deploy.yaml
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments/components/pipeline-service/staging  (mv-plnsrvce-to-infra)$ git status 
On branch mv-plnsrvce-to-infra
nothing to commit, working tree clean
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments/components/pipeline-service/staging  (mv-plnsrvce-to-infra)$
```

@divyans42 FYI

### CODE REVIEW

**Comment by gabemontero** [comment]
/hold

well I spoke too soon @enarha @savitaashture  .... the kustomize build which works for me locally fails here in the kube-linter / scan github action

I'll need to investigate

**Comment by gabemontero** [comment]
> /hold
> 
> well I spoke too soon @enarha @savitaashture .... the kustomize build which works for me locally fails here in the kube-linter / scan github action
> 
> I'll need to investigate

/hold cancel

simple typo from a file rename with the dashboards ... should work now @enarha @savitaashture

**Comment by gabemontero** [comment]
passing e2e's with the dev overlay @enarha @savitaashture :-)

**Comment by gabemontero** [comment]
so pipeline svc did not come up in the e2e's (after passing before) with the dev overlay when I tried to pull in the changes from https://github.com/redhat-appstudio/infra-deployments/pull/4275/files so I have reverted them.

I did ask them to also change the dev overlay in their PR so they can go through the same validation.

**Comment by gabemontero** [comment]
ok e2e tests green again @enarha @savitaashture

**Comment by enarha** [comment]
The other thing to decide is when we want to merge that. I would say we either merge it today or wait for Monday. I'm OK with either option.

**Comment by gabemontero** [comment]
> The other thing to decide is when we want to merge that. I would say we either merge it today or wait for Monday. I'm OK with either option.

I'm on PTO tomorrow so how I'll wait until late Sunday or Monday @enarha .  Thanks.

**Pull request merged**
