### PR TITLE
update build readme shared resoruces section to note PLNSRVCE-251 protection

### PR DESCRIPTION
**Pull request by gabemontero**
It occurred to me @Michkov that some mention of the [PLNSRVCE-251](https://issues.redhat.com//browse/PLNSRVCE-251) protection in your recent README updates per [PLNSRVCE-535](https://issues.redhat.com//browse/PLNSRVCE-535) is warranted for completeness.

If you agree and we get to a consensus on the precise wording of the change, we can officially associate with 535

### CODE REVIEW

**Comment by gabemontero** [comment]
looks like the CI job start failed ... will try to close / reopen the PR

**Comment by gabemontero** [comment]
oh ... it skips the e2e if it is just a readme update:  https://github.com/openshift/release/blob/master/ci-operator/config/redhat-appstudio/infra-deployments/redhat-appstudio-infra-deployments-main.yaml#L26

**Comment by Michkov** [comment]
Since we want to switch completely to PipelinesAsCode soon then not sure if we need to document this, with PaC it will not be valid anymore

**Comment by gabemontero** [comment]
ok I'm fine with tracking the PaC progress where ultimately the PLNSRVCE-251 logic is reverted

closing

**Pull request closed without merging**
