### PR TITLE
feat(RHTAP-965): Add dashboard to track PipelineRuns and TaskRuns

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by avi-biton** [comment]
@jhutar The dashboards json files should be located in your team's repository, please take a look at `o11y` example:
https://github.com/redhat-appstudio/infra-deployments/tree/main/components/monitoring/grafana/base/o11y
https://github.com/redhat-appstudio/o11y/tree/main/grafana

**Comment by avi-biton** [comment]
> I assume it is because of flexibility - it is easier to change that dashboard in our repo than in infra-deployments right?
Yes you are right


> Are there some requirements on the repos? I assume they just have to public.
Thats about it

> If we later update the json in our repo, how do we propagate the change to Stage (or Prod)?
You simply point it to the right commit sha in `infra-deployments` kustomize file  
See example: https://github.com/redhat-appstudio/infra-deployments/blob/main/components/monitoring/grafana/base/o11y/kustomization.yaml#L4

**Comment by jhutar** [comment]
Oh, so if I would have `?ref=main` (or `?ref=HEAD`?) it would not work?

**Comment by Michkov** [comment]
@jhutar @avi-biton in this case it's dashobard for PipelineRuns and TaskRuns so in theory it could be part of [pipeline-service](https://github.com/openshift-pipelines/pipeline-service) CC @Roming22 

I don't think that it would be necessary to create separate repository just for one dashboard - in that case I would add it directly to infra-deployments.

**Comment by avi-biton** [comment]
> Oh, so if I would have `?ref=main` (or `?ref=HEAD`?) it would not work?

I didn't try that, but you can test it in the development cluster

**Comment by avi-biton** [comment]
> @jhutar @avi-biton in this case it's dashobard for PipelineRuns and TaskRuns so in theory it could be part of [pipeline-service](https://github.com/openshift-pipelines/pipeline-service) CC @Roming22
> 
> I don't think that it would be necessary to create separate repository just for one dashboard - in that case I would add it directly to infra-deployments.

I agree, if no such repository exists, the dashboard can be added directly to `infra-deployments`, no need to create a special repository for that

**Comment by jhutar** [comment]
Hello. I have created extra repo. Our team now owns 3 dashboards and we plan to continue on them. Please let me know if current status looks good.

**Comment by Roming22** [comment]
@Michkov Different team will need different dashboards to access the information relevant to their work. I would not be surprised that some of the data in those dashboards are duplicated, and I personally prefer that over having to remember which graph is in which dashboard.

We can discuss this offline in an arch call if necessary.

**Comment by jhutar** [comment]
Hello @avi-biton or anybody. Could you please re-review?

**Comment by Michkov** [comment]
Previous e2e-test passed - https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1852/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1669280093983215616

Merging

**Pull request merged**
