### PR TITLE
Update HAS to bd09eb52ee6b87f0543ebca701dbc795eb017929

### PR DESCRIPTION
**Pull request by johnmcollier**
Signed-off-by: John Collier <jcollier@redhat.com>

### CODE REVIEW

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by Michkov** [comment]
@johnmcollier I do not think that retest will work since it's failing on [Message: "Internal error occurred: failed calling webhook \"mapplication.kb.io\": failed to call webhook...]( https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/249/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1512138832261156864#1:build-log.txt%3A189)

**Comment by johnmcollier** [comment]
@flacatus Any idea what's going on here? The error in the logs is not being seen on the e2e tests in our repo

**Pull request merged**
