### PR TITLE
Bump hac-dev, chrome service, chrome frontend tags

### PR DESCRIPTION
**Pull request by ashwindasr**
Mainly to get https://github.com/openshift/hac-dev/pull/926 in, but bumping the others as well.

### CODE REVIEW

**Comment by ashwindasr** [comment]
Thanks @hugares, since I don't have the permissions, you may have to force push like last time https://github.com/redhat-appstudio/infra-deployments/pull/3632

**Comment by hugares** [comment]
> Thanks @hugares, since I don't have the permissions, you may have to force push like last time #3632

Sure, I can do that. There is an issue with kustomize build of prod overlay:
```
Error: invalid Kustomization: json: cannot unmarshal number into Go struct field Image.images.newTag of type string
```

**Comment by ashwindasr** [comment]
Yeah looks we we got the tag as all numbers https://quay.io/repository/cloudservices/chrome-service?tab=tags

**Comment by ashwindasr** [comment]
when you're force pushing, can you use the tag before this one, thats alpha-numberic so should be good

**Comment by hugares** [comment]
> when you're force pushing, can you use the tag before this one, thats alpha-numberic so should be good

Can you comment in the file with the exact tags I should use, so I put the right ones

**Comment by ashwindasr** [comment]
updated PR, pushed the new tag

**Review by hugares — APPROVED** [review]
/lgtm

**Comment by hugares** [comment]
> Thanks @hugares, since I don't have the permissions, you may have to force push like last time

Looks like this will not be needed. Since I put the /ok-to-test and you pushed again, the check that used to block things is not there

**Comment by ashwindasr** [comment]
looks like `appstudio-e2e-tests` failure is not a flake. any ideas @hugares

**Comment by ashwindasr** [comment]
/hold

Since @sahil143 had mentioned that there are other big changes that were merged this week, which are still yet to be tested on staging.

**Comment by ashwindasr** [comment]
/unhold

Since testing has finished

**Pull request merged**
