### PR TITLE
Dont Merge. Verify PLNSRVCE-1625 on pipeline-service

### PR DESCRIPTION
**Pull request by jkhelil**
- This PR aims to run e2e and verify https://github.com/openshift-pipelines/pipeline-service/pull/937

### CODE REVIEW

**Comment by gabemontero** [comment]
e2e's are currently busted with the bitnami image / postgresql / results issue the started today that @avinal is looking into

my best guess based on the kube-linter error though @jkhelil is that you have to rebase either this branch, your pipeline-service repro branch, or both:

```

Run find argo-cd-apps components -name 'kustomization.yaml' ! -path '*/k-components/*' | \
Error when running kustomize build for components/pipeline-service/development: Error: replace operation does not apply: doc is missing path: /spec/pipeline/options/deployments/tekton-operator-proxy-webhook/spec/replicas: missing value
Error: Process completed with exit code 123.
```

in the main branch of this repo we have https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/development/update-tekton-config-performance.yaml#L30-L33 that is modifying the replicas for the tekton-operator-proxy-webhook and then over in https://github.com/openshift-pipelines/pipeline-service/blob/main/operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml#L56-L59 is where we make the tektonconfig change available to be modified

**Comment by gabemontero** [comment]
> e2e's are currently busted with the bitnami image / postgresql / results issue the started today that @avinal is looking into
> 
> my best guess based on the kube-linter error though @jkhelil is that you have to rebase either this branch, your pipeline-service repro branch, or both:
> 
> ```
> 
> Run find argo-cd-apps components -name 'kustomization.yaml' ! -path '*/k-components/*' | \
> Error when running kustomize build for components/pipeline-service/development: Error: replace operation does not apply: doc is missing path: /spec/pipeline/options/deployments/tekton-operator-proxy-webhook/spec/replicas: missing value
> Error: Process completed with exit code 123.
> ```
> 
> in the main branch of this repo we have https://github.com/redhat-appstudio/infra-deployments/blob/main/components/pipeline-service/development/update-tekton-config-performance.yaml#L30-L33 that is modifying the replicas for the tekton-operator-proxy-webhook and then over in https://github.com/openshift-pipelines/pipeline-service/blob/main/operator/gitops/argocd/pipeline-service/openshift-pipelines/tekton-config.yaml#L56-L59 is where we make the tektonconfig change available to be modified

this part looks good now @jkhelil cool deal

**Comment by Roming22** [comment]
@jkhelil I believe this PR is obsolete. If true, please close it.

**Pull request closed without merging**
