### PR TITLE
PLNSRVCE-248: create shared secret redhat-appstudio-user-workload

### PR DESCRIPTION
**Pull request by gabemontero**
Let's see if I correctly interpreted your instructions @Michkov 

Running `export MODE=preview; ./hack/bootstrap-cluster.sh $MODE`, after that completes, I got the following:

```
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments  (jira-plnsrvce-248)$ oc get sharedsecret
NAME                             AGE
redhat-appstudio-staginguser     0s
redhat-appstudio-user-workload   0s
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments  (jira-plnsrvce-248)$ oc get clusterrole pipelines-scc-clusterrole -o yaml 
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"ClusterRole","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true"},"labels":{"app.kubernetes.io/instance":"build"},"name":"pipelines-scc-clusterrole"},"rules":[{"apiGroups":["security.openshift.io"],"resourceNames":["pipelines-scc"],"resources":["securitycontextconstraints"],"verbs":["use"]},{"apiGroups":["sharedresource.openshift.io"],"resourceNames":["redhat-appstudio-user-workload"],"resources":["sharedsecrets"],"verbs":["use"]},{"apiGroups":["security.openshift.io"],"resourceNames":["csi-scc"],"resources":["securitycontextconstraints"],"verbs":["use"]}]}
  creationTimestamp: "2022-05-10T16:39:31Z"
  labels:
    app.kubernetes.io/instance: build
  name: pipelines-scc-clusterrole
  ownerReferences:
  - apiVersion: operator.tekton.dev/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: TektonInstallerSet
    name: rhosp-rbac-glsz9
    uid: 70e75267-7fc3-459e-b945-26c93beccdfe
  resourceVersion: "185568"
  uid: 807fc56d-fdfd-47da-b065-70092057efd0
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - pipelines-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
- apiGroups:
  - sharedresource.openshift.io
  resourceNames:
  - redhat-appstudio-user-workload
  resources:
  - sharedsecrets
  verbs:
  - use
- apiGroups:
  - security.openshift.io
  resourceNames:
  - csi-scc
  resources:
  - securitycontextconstraints
  verbs:
  - use
gmontero ~/go/src/github.com/redhat-appstudio/infra-deployments  (jira-plnsrvce-248)$
```

### CODE REVIEW

**Comment by gabemontero** [comment]
Interestingly, I tweaked my sharedresource example taskrun to use the pipeline SA and use the new `redhat-apppstudio-user-workload` sharedsecret and it did not work with these just these changes.  Got the typical forbidden user errors.

I had to create an explicit clusterrolebinding for the pipeline SA in my test namespace:

```
$ oc adm policy add-cluster-role-to-user pipelines-scc-clusterrole -z pipeline -n my-csi-app-namespace 
clusterrole.rbac.authorization.k8s.io/pipelines-scc-clusterrole added: "pipeline"
$
```

and then it worked.

**Comment by gabemontero** [comment]
from the openshift-gitops-operator in the failed e2e's mustgather:

```
   message: 'installing: waiting for deployment gitops-operator-controller-manager
      to become ready: deployment "gitops-operator-controller-manager" not available:
      Deployment does not have minimum availability.'

```

must gather does not have pod logs for the openshift-operators namespace though

**Comment by gabemontero** [comment]
> Interestingly, I tweaked my sharedresource example taskrun to use the pipeline SA and use the new `redhat-apppstudio-user-workload` sharedsecret and it did not work with just these changes. Got the typical forbidden user errors.
> 
> I had to create an explicit clusterrolebinding for the pipeline SA in my test namespace:
> 
> ```
> $ oc adm policy add-cluster-role-to-user pipelines-scc-clusterrole -z pipeline -n my-csi-app-namespace 
> clusterrole.rbac.authorization.k8s.io/pipelines-scc-clusterrole added: "pipeline"
> $
> ```
> 
> where that is
> 
> ```
> $ oc get clusterrolebinding pipelines-scc-clusterrole -o yaml 
> apiVersion: rbac.authorization.k8s.io/v1
> kind: ClusterRoleBinding
> metadata:
>   creationTimestamp: "2022-05-10T20:04:31Z"
>   name: pipelines-scc-clusterrole
>   resourceVersion: "224394"
>   uid: 77538dd4-cdd0-4f42-83c9-01a777e9b9a9
> roleRef:
>   apiGroup: rbac.authorization.k8s.io
>   kind: ClusterRole
>   name: pipelines-scc-clusterrole
> subjects:
> - kind: ServiceAccount
>   name: pipeline
>   namespace: my-csi-app-namespace
> ```
> 
> and then it worked.

realized it might be a "have to use `oc new-project`" thing

will confirm/refute tomorrow

**Comment by gabemontero** [comment]
> > Interestingly, I tweaked my sharedresource example taskrun to use the pipeline SA and use the new `redhat-apppstudio-user-workload` sharedsecret and it did not work with just these changes. Got the typical forbidden user errors.
> > I had to create an explicit clusterrolebinding for the pipeline SA in my test namespace:
> > ```
> > $ oc adm policy add-cluster-role-to-user pipelines-scc-clusterrole -z pipeline -n my-csi-app-namespace 
> > clusterrole.rbac.authorization.k8s.io/pipelines-scc-clusterrole added: "pipeline"
> > $
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > where that is
> > ```
> > $ oc get clusterrolebinding pipelines-scc-clusterrole -o yaml 
> > apiVersion: rbac.authorization.k8s.io/v1
> > kind: ClusterRoleBinding
> > metadata:
> >   creationTimestamp: "2022-05-10T20:04:31Z"
> >   name: pipelines-scc-clusterrole
> >   resourceVersion: "224394"
> >   uid: 77538dd4-cdd0-4f42-83c9-01a777e9b9a9
> > roleRef:
> >   apiGroup: rbac.authorization.k8s.io
> >   kind: ClusterRole
> >   name: pipelines-scc-clusterrole
> > subjects:
> > - kind: ServiceAccount
> >   name: pipeline
> >   namespace: my-csi-app-namespace
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and then it worked.
> 
> realized it might be a "have to use `oc new-project`" thing
> 
> will confirm/refute tomorrow

@sbose78 @Michkov and I are discussing in slack.  Executive summary: there are reconciler timing delays.  Things work eventually with generic namespace creation, but work faster with `oc new-project`

**Comment by gabemontero** [comment]
Summary of my testing today:

- the `pipelines-scc-clusterrole` settings are oscillating between our overrides here and the base setting provided by openshift pipelines ... that explains the intermittent behavior.  It is not a "delay" per say.  I had a watch running on that clusterrole so I could catch its oscillation

- I have not pushed the changes from this  branch's / PR's copy on my laptop yet, but I tried @Michkov idea of creating a new ClusterRole, with a ClusterRoleBinding assigning these permissions to both `system:authenticated` and `system:unauthenticated` and even still the `pipeline` SA in my test namespace cannot use the shared resource.

- I can only get it to work with by creating a role binding that explicitly calls out the `pipeline` SA in my tet namespace as a subject 

Will continue discussions with @sbose78 and @Michkov in slack, team meetings, and here to figure out where we want to go with this.

**Comment by gabemontero** [comment]
OK this approach works:
- create new clusterrole
- aggregate to edit role (pipeline SA gets the edit role when it gets created in new projects/namespaces)

PTAL when you are next online @Michkov - I think this is ready to merge, pending any suggestions you might have on names or other details here.  Thanks.

**Review by Michkov — APPROVED** [review]

**Pull request merged**
