### PR TITLE
Increase memory and CPU limits for HAS

### PR DESCRIPTION
**Pull request by johnmcollier**
Increases resource limits for HAS in staging.

### CODE REVIEW

**Review by maysunfaisal — APPROVED** [review]

**Review by sbose78 — APPROVED** [review]

**Comment by sbose78** [comment]
Ah system had slipped in

**Comment by johnmcollier** [comment]
I ended up needed to add `namespace: system` back in, otherwise the patch doesn't work correctly (I assume because the resource it's trying to patch, has `namespace: system` set in it too?)

I verified that by running `kustomize build`, the actualy namespace HAS is deployed in is still `application-service` though.

**Comment by sbose78** [comment]
taking one final look before merging.

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
