### PR TITLE
Disable CSV Copy for all the operators from OLM

### PR DESCRIPTION
**Pull request by bamachrn**
This PR
* Disables copying CSVs from OLM for all the stonesoup clusters

### CODE REVIEW

**Comment by amfred** [comment]
This looks like what we want to do (see the thread on #wg-stonestone-platform) but let's get Gal's review.

**Comment by amfred** [comment]
Also waiting for a passing test

**Comment by bamachrn** [comment]
its taking more than 2hours

**Comment by Michkov** [comment]
```
'one or more objects failed to apply, reason: ApplicationSet.argoproj.io "disable-csvcopy" is invalid: spec.generators[0].merge.generators[0].clusters.values: Invalid value: "array": spec.generators[0].merge.generators[0].clusters.values in body must be of type object: "array" (retried 5 times).'
```

**Review by amfred — APPROVED** [review]
Let's see if this really applies the change to all namespaces.

**Pull request merged**
