### PR TITLE
update respone time formula proxy metrics

### PR DESCRIPTION
**Pull request by ranakan19**
Updated the respone time calculation formula to segregate by status_code  onto numerator and denominator while calculating average.

### CODE REVIEW

**Review by mfrancisc — APPROVED** [review]
Thanks for fixing it 🏅

**Review by amisstea — CHANGES_REQUESTED** [review]
@ranakan19 it looks like your rebase didn't work as planned. Please remove the extra commits.

**Comment by hugares** [comment]
> @ranakan19 it looks like your rebase didn't work as planned. Please remove the extra commits.

I did the rebase in another PR as I could not update that one: https://github.com/redhat-appstudio/infra-deployments/pull/3232

closing this one

**Pull request closed without merging**
