### PR TITLE
Consume build-templates-bundle from build-definitions

### PR DESCRIPTION
**Pull request by Michkov**
Use pipeline from tekton bundle generated by
redhat-appstudio/build-definitions .

### CODE REVIEW

**Comment by sbose78** [comment]
Hi @Michkov , Did you have a chance to run these pipelines after making these changes to see if they work fine?

**Comment by sbose78** [comment]
Asking because the CI check here doesn;t do a lot in that area yet :)

**Comment by jduimovich** [comment]
@sbose78 @Michkov This build won't work yet, need to update the docker build ignores the dockefile param at the moment :(

**Review by jduimovich — COMMENTED** [review]
This will work fine :) when the docker-build pipeline def is fixed to reference the dockerfile param in the buildah build.

**Comment by Michkov** [comment]
@sbose78 Yes, tested locally on level of applying changes via gitops and simulating `curl` to trigger start of pipelinerun, pipelinerun started and failed on missing credentials, which was expected.

**Comment by sbose78** [comment]
So, should we merge this? 🤔

**Comment by jduimovich** [comment]
How did this work @Michov ? the docker-build params don't match the names in the triggers.

**Comment by jduimovich** [comment]
Yes, the current pipelines and the ones in .tekton have small mismatched things (param names) and under inspection, the docker-build one is broken as it sadly ignores the params.

**Comment by jduimovich** [comment]
The tkn command is weird, I guess they look at the PRun and describe the passed parms and not at the pipeline itself and describe the expected params

**Comment by Michkov** [comment]
Updated to v0.1.3. Tested till build of the container, failed with push which is expected.

**Comment by sbose78** [comment]
Is this good to merge ?

**Comment by jduimovich** [comment]
Yes,  this is ready. I tested the pipeline manually via build scripts  `./build.sh https://github.com/redhat-appstudio/managed-gitops` and it succeeded

**Comment by Michkov** [comment]
Updated to build-bundle v0.1.4, tested using EventListener, pipelineRun started, container built, failed on pushing since I do not have right credentials. This can be merged.

**Pull request merged**
