### PR TITLE
managed-gitops update: Cherry pick #2401 to staging only: update components/gitops/staging/base/kustomization.yaml

### PR DESCRIPTION
**Pull request by jgwest**
Cherry pick only the staging commit for https://github.com/redhat-appstudio/infra-deployments/pull/2401

### CODE REVIEW

**Comment by jgwest** [comment]
/retest
No github tokens available

**Comment by jgwest** [comment]
pod timeout
/retest

**Comment by jgwest** [comment]
CI error
/retest

**Comment by dheerajodha** [comment]
I could save some `/ retest` cycles by merging this rn by adding a `lgtm` label (all tests passed, the branch is up-to-date) but I'm not sure if that's the right thing to do in these kinds of situations since I'm not the PR author nor do I have any context on this PR (it could be waiting for another PR to get merged or something).

**Pull request merged**
