### PR TITLE
remove references to tekton-chains namespace from production

### PR DESCRIPTION
**Pull request by ramessesii2**
- The `tekton-chains` namespace is obsolete with the Tekton Chains controller deployed with openshift-pipelines operator.

- follow up on #2364, 
- an analysis of the staging (member cluster): don't see a regression looking at the chains logs and the PipelineRuns are signed as usual by chains; verifies #2364's success in staging. This PR is meant to promote the changes to production.

### CODE REVIEW

**Comment by ramessesii2** [comment]
Latest CI failure shows this :
```


: Import the release payload "latest" from an external source expand_less | 1m27s
-- | --
{  unable to import image stream stable: could not resolve imagestream stable: Get "https://172.30.0.1:443/apis/image.openshift.io/v1/namespaces/ci-op-3w4b6i4n/imagestreams/stable": http2: client connection lost}

```

**Review by gabemontero — APPROVED** [review]

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
per https://redhat-internal.slack.com/archives/C032EJ007C0/p1695829839032639 I'm going to combine this PR with https://github.com/redhat-appstudio/infra-deployments/pull/2463

/hold

**Comment by gabemontero** [comment]
/close

I have cherry-picked the commit in this PR from @ramessesii2 into #2463

**Pull request closed without merging**
