### PR TITLE
Add utility to generate deploy.yaml

### PR DESCRIPTION
**Pull request by Roming22**
rh-pre-commit.version: 2.1.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Review by gabemontero — COMMENTED** [review]
IIRC from a recent arch call it appears the other Konflux components are not going to the model put into place for pipeline-service anytime soon ....is that correct?

if so, perhaps rename the script to `generate-pipeline-service-deploy-config.sh

but if other components are going to employ the model recently established for pipeline-service, sure keep the name generic

otherwise, if I parse the bash correctly, I think this achieves what we have been doing manually, so 

lgtm

**Comment by Roming22** [comment]
We don't know what the future holds. It won't do anything on components that do not follow the `deploy.yaml` model.

So I'd rather keep the name generic so that we don't have to rename it in the future.

**Comment by gabemontero** [comment]
> We don't know what the future holds. It won't do anything on components that do not follow the `deploy.yaml` model.
> 
> So I'd rather keep the name generic so that we don't have to rename it in the future.

Ok I'm fine with that.  Thanks for clarifying.

**Review by gabemontero — APPROVED** [review]
/lgtm

**Pull request merged**
