### PR TITLE
Move renovate config to the renovate repo

### PR DESCRIPTION
**Pull request by querti**
Move renovate config to the renovate repo
    
Renovate config for MintMaker will now be in a different repo. Changing
which version of the configration should be deployed can be done by
changing the git ref of the config.
    
Related PR: https://github.com/konflux-ci/mintmaker/pull/32
    
Refers to [CWFHEALTH-3206](https://issues.redhat.com//browse/CWFHEALTH-3206)

### CODE REVIEW

**Comment by querti** [comment]
@qixiang @nvtnlucie @staticf0x @gnaponie please review

**Comment by qixiang** [comment]
@querti could you update the commit message? the mintmaker-config repo is referenced.

**Comment by querti** [comment]
> @querti could you update the commit message? the mintmaker-config repo is referenced.

Fixed, thanks

**Review by qixiang — APPROVED** [review]

**Pull request merged**
