### PR TITLE
add hacbs release-service manager

### PR DESCRIPTION
**Pull request by johnbieren**
Signed-off-by: Johnny Bieren <jbieren@redhat.com>

### CODE REVIEW

**Comment by johnbieren** [comment]
Relates to https://github.com/redhat-appstudio/release-service/pull/117

**Comment by johnbieren** [comment]
@Michkov can you take a look when you have time?

**Review by Michkov — APPROVED** [review]
Manager pod starts successfully

**Comment by Michkov** [comment]
getting these errors/warnings:
```
E1014 13:33:11.278571 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ApplicationSnapshotEnvironmentBinding: unknown (get applicationsnapshotenvironmentbindings.appstudio.redhat.com)
W1014 13:33:12.115780 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.ApplicationSnapshotEnvironmentBinding: applicationsnapshotenvironmentbindings.appstudio.redhat.com is forbidden: User "system:serviceaccount:release-service:controller-manager" cannot list resource "applicationsnapshotenvironmentbindings" in API group "appstudio.redhat.com" at the cluster scope: access denied
E1014 13:33:12.115812 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.ApplicationSnapshotEnvironmentBinding: failed to list *v1alpha1.ApplicationSnapshotEnvironmentBinding: applicationsnapshotenvironmentbindings.appstudio.redhat.com is forbidden: User "system:serviceaccount:release-service:controller-manager" cannot list resource "applicationsnapshotenvironmentbindings" in API group "appstudio.redhat.com" at the cluster scope: access denied
E1014 13:33:48.419923 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Release: unknown (get releases.appstudio.redhat.com)
E1014 13:33:51.374803 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.PipelineRun: unknown (get pipelineruns.tekton.dev)
W1014 13:33:52.736114 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1beta1.PipelineRun: pipelineruns.tekton.dev is forbidden: User "system:serviceaccount:release-service:controller-manager" cannot list resource "pipelineruns" in API group "tekton.dev" at the cluster scope: access denied
E1014 13:33:52.736156 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1beta1.PipelineRun: failed to list *v1beta1.PipelineRun: pipelineruns.tekton.dev is forbidden: User "system:serviceaccount:release-service:controller-manager" cannot list resource "pipelineruns" in API group "tekton.dev" at the cluster scope: access denied
E1014 13:35:16.296493 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Component: unknown (get components.appstudio.redhat.com)
W1014 13:35:17.548884 1 reflector.go:324] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: failed to list *v1alpha1.Component: components.appstudio.redhat.com is forbidden: User "system:serviceaccount:release-service:controller-manager" cannot list resource "components" in API group "appstudio.redhat.com" at the cluster scope: access denied
E1014 13:35:17.548912 1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.24.3/tools/cache/reflector.go:167: Failed to watch *v1alpha1.Component: failed to list *v1alpha1.Component: components.appstudio.redhat.com is forbidden: User "system:serviceaccount:release-service:controller-manager" cannot list resource "components" in API group "appstudio.redhat.com" at the cluster scope: access denied
```
But that can be fixed/investigated later.

**Pull request merged**
