### PR TITLE
Change unit from percent to none

### PR DESCRIPTION
**Pull request by divyansh42**
Fix from the previous PR https://github.com/redhat-appstudio/infra-deployments/pull/4338

### CODE REVIEW

**Comment by divyansh42** [comment]
@gabemontero FYI 
Please take a look

**Review by gabemontero — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
Yeah @divyansh42 closing and then reopening this PR may do the trick wrt getting that `Red Hat Konflux` job sorted out

trying it now

**Comment by gabemontero** [comment]
yeah that job is still stuck after closing / reopening the PR @divyansh42 

Wednesday your time accept that invite if you haven't, create a new branch/pr and let's see how that does

**Comment by hugares** [comment]
> yeah that job is still stuck after closing / reopening the PR @divyansh42
> 
> Wednesday your time accept that invite if you haven't, create a new branch/pr and let's see how that does

@divyansh42 accepted the invite already, all you have to do is to update this PR with new commit to trigger checks again by either rebasing your branch or amending the commit if you are already on tip of the main branch

**Comment by gabemontero** [comment]
> > yeah that job is still stuck after closing / reopening the PR @divyansh42
> > Wednesday your time accept that invite if you haven't, create a new branch/pr and let's see how that does
> 
> @divyansh42 accepted the invite already, all you have to do is to update this PR with new commit to trigger checks again by either rebasing your branch or amending the commit if you are already on tip of the main branch

yep that seems to have cleared it out thanks @hugares

**Review by gabemontero — APPROVED** [review]
/lgtm

**Pull request merged**
