### PR TITLE
Promote integration-service from staging to production

### PR DESCRIPTION
**Pull request by dirgim**
Included PRs:
 - https://github.com/redhat-appstudio/integration-service/pull/552
 - https://github.com/redhat-appstudio/integration-service/pull/558
 - https://github.com/redhat-appstudio/integration-service/pull/561
 - https://github.com/redhat-appstudio/integration-service/pull/559
 - https://github.com/redhat-appstudio/integration-service/pull/560
 - https://github.com/redhat-appstudio/integration-service/pull/553
 - https://github.com/redhat-appstudio/integration-service/pull/556
 - https://github.com/redhat-appstudio/integration-service/pull/546
 - https://github.com/redhat-appstudio/integration-service/pull/555
 - https://github.com/redhat-appstudio/integration-service/pull/554
 - https://github.com/redhat-appstudio/integration-service/pull/521

### CODE REVIEW

**Review by MartinBasti — APPROVED** [review]

**Comment by dheerajodha** [comment]
CI is blocked due to [KFLUXBUGS-1104](https://issues.redhat.com/browse/KFLUXBUGS-1104)

**Review by jsztuka — APPROVED** [review]
/lgtm

**Pull request merged**
