### PR TITLE
fix: rename integration configMap console-url to integration-config

### PR DESCRIPTION
**Pull request by hongweiliu17**
* rename integration configMap console-url to integration-config

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Review by MartinBasti — APPROVED** [review]

**Comment by kasemAlem** [comment]
blocked by bug [KFLUXBUGS-1314](https://issues.redhat.com/browse/KFLUXBUGS-1314)

**Review by kasemAlem — APPROVED** [review]

**Pull request merged**
