### PR TITLE
Add Results ServiceMonitor to pipeline-service

### PR DESCRIPTION
**Pull request by enarha**
Adds two service monitors to pipeline-service for Tekton Results api and watcher.

### CODE REVIEW

**Comment by enarha** [comment]
This is WIP as we need two labels for the api and watcher services added upstream to get propagated downstream and into infra-deployments.

**Comment by gbenhaim** [comment]
@enarha, @yftacherzog is working on a guide about how to add service monitors. I think this PR is a good candidate for testing it.

**Comment by enarha** [comment]
Sure. I can use that.
There is also https://github.com/redhat-appstudio/infra-deployments/blob/main/components/monitoring/README.md

**Comment by yftacherzog** [comment]
> Sure. I can use that. There is also https://github.com/redhat-appstudio/infra-deployments/blob/main/components/monitoring/README.md

That's the one I updated. I also shared a demo with you that we plan to be presented soon.

**Comment by enarha** [comment]
@yftacherzog It's been a while, but I just updated the PR based on the presentation you've shared with me.

**Comment by gabemontero** [comment]
/assign @adambkaplan 
/assign @Roming22 

currently only these two are in the owners file, and thus are the only two that can officially approve via 

/approve

**Review by gabemontero — APPROVED** [review]

**Comment by enarha** [comment]
@Roming22 Updated.

**Review by Roming22 — APPROVED** [review]
/lgtm

**Pull request merged**
