### PR TITLE
chore(STONEO11Y-81): enable user workload monitoring on dev

### PR DESCRIPTION
**Pull request by yftacherzog**
Enable Prometheus for user workload monitoring in dev and reinstate the relevant argoCD apps in dev, stage and prod.

Also clean up old user workload configs

### CODE REVIEW

**Comment by yftacherzog** [comment]
@gbenhaim @hmariset @avi-biton please take a look

**Comment by hmariset** [comment]
LGTM

**Comment by yftacherzog** [comment]
@gbenhaim @amisstea @avi-biton @Omeramsc please take a look

**Review by Omeramsc — APPROVED** [review]
LGTM

**Review by amisstea — APPROVED** [review]

**Pull request merged**
