### PR TITLE
[WIP] Fixed prometheus secrets for servicemonitors

### PR DESCRIPTION
**Pull request by bamachrn**
This PR
* stream lines all the servicemonitors to use the similar authentication for scraping
* adds the token secret as patch

### CODE REVIEW

**Comment by gbenhaim** [comment]
copied from slack

gbenhaim
  [27 minutes ago](https://redhat-internal.slack.com/archives/C04F4NE15U1/p1678259528905259?thread_ts=1678258096.708839&cid=C04F4NE15U1)
the Prometheus pod run with that service account?


gbenhaim
  [24 minutes ago](https://redhat-internal.slack.com/archives/C04F4NE15U1/p1678259721486549?thread_ts=1678258096.708839&cid=C04F4NE15U1)
the prometheus-k8s is automatically mounted to the prom pod


gbenhaim
  [23 minutes ago](https://redhat-internal.slack.com/archives/C04F4NE15U1/p1678259763468359?thread_ts=1678258096.708839&cid=C04F4NE15U1)
so it surprises me that you need to tell it where to find the token explicitly (edited) 


gbenhaim
  [20 minutes ago](https://redhat-internal.slack.com/archives/C04F4NE15U1/p1678259964961519?thread_ts=1678258096.708839&cid=C04F4NE15U1)
what happens if you don't specify the token explicitly?


gbenhaim
  [20 minutes ago](https://redhat-internal.slack.com/archives/C04F4NE15U1/p1678259995459939?thread_ts=1678258096.708839&cid=C04F4NE15U1)
I've been reading the docs, https://docs.openshift.com/container-platform/4.12/monitoring/configuring-the-monitoring-stack.html I don't see any mention about those configurations

**Review by gbenhaim — CHANGES_REQUESTED** [review]
let's try to skip this configuration. The token is automatically mounted to the Prom pod, I think it should be enough.

**Comment by amfred** [comment]
I'll let Gal decide when this one is ready to go.

**Comment by gbenhaim** [comment]
this PR is not needed anymore since we found another way for dynamically creating the secret https://github.com/redhat-appstudio/infra-deployments/tree/main/components/monitoring#2-service-monitors

**Pull request closed without merging**
