### PR TITLE
Remove BuildPipelineSelector from infra-deployments

### PR DESCRIPTION
**Pull request by rcerven**
[STONEBLD-2279](https://issues.redhat.com//browse/STONEBLD-2279)

### CODE REVIEW

**Review by mmorhun — APPROVED** [review]

**Comment by mmorhun** [comment]
I think we also need to clean scripts that update images in BuildPipelineSelector before merging this PR.

**Comment by rcerven** [comment]
> I think we also need to clean scripts that update images in BuildPipelineSelector before merging this PR.

https://github.com/konflux-ci/build-definitions/pull/1046

**Pull request merged**
