### PR TITLE
Update setup-nfs-quickcluster.sh to work with RHEL-8

### PR DESCRIPTION
**Pull request by Tojaj**
If restart of nfs.service fails, try to restart nfs-server.service instead.

### CODE REVIEW

**Comment by dirgim** [comment]
The change looks reasonable to me, but I'll defer to @scoheb and @johnbieren as the original authors of the script.

**Review by scoheb — APPROVED** [review]

**Review by kasemAlem — APPROVED** [review]

**Comment by hugares** [comment]
There is a job "Red Hat Konflux" cannot run... Forcing this change in as this script is not tested by the failing checks

**Pull request merged**
