### PR TITLE
Remove pipelines-as-code namespace refs production

### PR DESCRIPTION
**Pull request by enarha**
After switching to OSP 1.11, PaC is deployed through the OSP operator and into the openshift-pipelines namespace and the pipelines-as-code namespace is not needed anymore.
The change was verified in staging PR #2350.

### CODE REVIEW

**Comment by enarha** [comment]
@manish-jangra @gabemontero PTAL.

**Review by manish-jangra — DISMISSED** [review]
You can delete the directory pipelines-as-code in base/rbac

**Comment by gabemontero** [comment]
So the 2 e2e failures are 
```
 Summarizing 2 Failures:
  [FAIL] [spi-suite] SVPI-495 - Test automation to ensure that a user can't access and use secrets from another workspace [It] checks that a user's A pod deployed in workspace A should be able to construct an API request that reads code in the Github repo for workspace A [spi-suite, access-control]
  /tmp/tmp.bDIDKF8n9j/tests/spi/access-control.go:264
  [FAIL] [rhtap-demo-suite] DEVHAS-234: creates quarkus application(with dockerfile but not devfile) which is not included in AppStudio starter stack [It] waits for status-quarkus-io component (private: false) pipeline to be finished [rhtap-demo]
  /tmp/tmp.bDIDKF8n9j/tests/rhtap-demo/rhtap-demo.go:233
```

the SPI one is most likely not related to pipelines as code, but the rhtap-demo e2e does use pipelines as code as I recall.  You should look into the details of that failure @enarha and make sure it is not "pipelines as code related".

**Review by gabemontero — APPROVED** [review]

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
> So the 2 e2e failures are
> 
> ```
>  Summarizing 2 Failures:
>   [FAIL] [spi-suite] SVPI-495 - Test automation to ensure that a user can't access and use secrets from another workspace [It] checks that a user's A pod deployed in workspace A should be able to construct an API request that reads code in the Github repo for workspace A [spi-suite, access-control]
>   /tmp/tmp.bDIDKF8n9j/tests/spi/access-control.go:264
>   [FAIL] [rhtap-demo-suite] DEVHAS-234: creates quarkus application(with dockerfile but not devfile) which is not included in AppStudio starter stack [It] waits for status-quarkus-io component (private: false) pipeline to be finished [rhtap-demo]
>   /tmp/tmp.bDIDKF8n9j/tests/rhtap-demo/rhtap-demo.go:233
> ```
> 
> the SPI one is most likely not related to pipelines as code, but the rhtap-demo e2e does use pipelines as code as I recall. You should look into the details of that failure @enarha and make sure it is not "pipelines as code related".

well e2e's passed next time, so unrelated flake

**Pull request merged**
