### PR TITLE
update to 0.0.0-20220418-12-39-25

### PR DESCRIPTION
**Pull request by chrisahl**
Signed-off-by: Chris Ahl <cahl@redhat.com>

Part of https://issues.redhat.com/browse/CMCS-50

### CODE REVIEW

**Comment by Michkov** [comment]
New pod is failing with:
```
1.6503553837935367e+09	INFO	setup	Setup Installer
I0419 08:03:04.895203       1 request.go:665] Waited for 1.01845198s due to client-side throttling, not priority and fairness, request: GET:https://172.30.0.1:443/apis/autoscaling.openshift.io/v1beta1?timeout=32s
1.6503553870501251e+09	INFO	controller-runtime.metrics	Metrics server is starting to listen	{"addr": ":8080"}
1.650355387050465e+09	INFO	setup	Add Installer reconciler
1.6503553870517886e+09	INFO	controllers.Installer	setup installer manager
I0419 08:03:07.069907       1 recorder_in_memory.go:80] &Event{ObjectMeta:{dummy.16e73d7b0771c1c6  dummy    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},InvolvedObject:ObjectReference{Kind:Pod,Namespace:dummy,Name:dummy,UID:,APIVersion:v1,ResourceVersion:,FieldPath:,},Reason:CustomResourceDefinitionUpdateFailed,Message:Failed to update CustomResourceDefinition.apiextensions.k8s.io/clusterregistrars.singapore.open-cluster-management.io: CustomResourceDefinition.apiextensions.k8s.io "clusterregistrars.singapore.open-cluster-management.io" is invalid: spec.scope: Invalid value: "Cluster": field is immutable,Source:EventSource{Component:/usr/local/bin/cluster-registration,Host:,},FirstTimestamp:2022-04-19 08:03:07.069743558 +0000 UTC m=+3.506273272,LastTimestamp:2022-04-19 08:03:07.069743558 +0000 UTC m=+3.506273272,Count:1,Type:Warning,EventTime:0001-01-01 00:00:00 +0000 UTC,Series:nil,Action:,Related:nil,ReportingController:,ReportingInstance:,}
1.6503553870923188e+09	ERROR	setup	unable to create controller	{"controller": "Installer", "error": "\"crd/singapore.open-cluster-management.io_clusterregistrars.yaml\" (string): CustomResourceDefinition.apiextensions.k8s.io \"clusterregistrars.singapore.open-cluster-management.io\" is invalid: spec.scope: Invalid value: \"Cluster\": field is immutable", "errorVerbose": "\"crd/singapore.open-cluster-management.io_clusterregistrars.yaml\" (string): CustomResourceDefinition.apiextensions.k8s.io \"clusterregistrars.singapore.open-cluster-management.io\" is invalid: spec.scope: Invalid value: \"Cluster\": field is immutable\ngithub.com/stolostron/cluster-registration-operator/controllers/installer.(*ClusterRegistrarReconciler).SetupWithManager\n\t/workspace/controllers/installer/installer_controller.go:457\ngithub.com/stolostron/cluster-registration-operator/cmd/installer.(*installerOptions).run\n\t/workspace/cmd/installer/main.go:92\ngithub.com/stolostron/cluster-registration-operator/cmd/installer.NewInstaller.func1\n\t/workspace/cmd/installer/main.go:52\ngithub.com/spf13/cobra.(*Command).execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974\ngithub.com/spf13/cobra.(*Command).Execute\n\t/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902\nmain.main\n\t/workspace/main.go:32\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1581"}
github.com/stolostron/cluster-registration-operator/cmd/installer.(*installerOptions).run
	/workspace/cmd/installer/main.go:93
github.com/stolostron/cluster-registration-operator/cmd/installer.NewInstaller.func1
	/workspace/cmd/installer/main.go:52
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main
	/workspace/main.go:32
runtime.main
	/usr/local/go/src/runtime/proc.go:255
```

**Comment by chrisahl** [comment]
slack conversion about manual cleanup of old CRD - https://coreos.slack.com/archives/C02CTEB3MMF/p1650390429018189

**Comment by chrisahl** [comment]
This is ready to merge an I have folks who can do the manual cleanup of CRD on staging.  

For now the workaround for update is to:

- delete the old replicasets in namespace cluster-reg-config
- delete the old CRD clusterregistrars.singapore.open-cluster-management.io 
- delete the failing pod in namespace cluster-reg-config
The pod will restart and install the new CRD and all is well...

**Pull request merged**
