### PR TITLE
HACBS 45 - Add YAML lint documentation

### PR DESCRIPTION
**Pull request by robnester-rh**
Adding documentation to README regarding yamllint installation and
usage to validate kube/openshift resources.

Signed-off-by: Rob Nester <rnester@redhat.com>

### CODE REVIEW

**Comment by robnester-rh** [comment]
@simonbaird if you wouldn't mind taking a look at your convenience.

**Comment by simonbaird** [comment]
It's okay, but:

1. I got about 300 errors (see below) in pipeline-quay-demo.yaml, yet it looks okay to me. Not sure why exactly, but should we fix it in this commit?
2. Do we need a .yamllint config file to specify our linting rules? E.g. do we really want 80 char line limit?
3. How about a little script to lint all our yaml, something like:

    git ls-files *.yaml | xargs -n1 yamllint

```
pipeline-quay-demo.yaml
  8:3       error    wrong indentation: expected 4 but found 2  (indentation)
  26:81     error    line too long (88 > 80 characters)  (line-length)
  29:3      error    wrong indentation: expected 4 but found 2  (indentation)
  38:81     error    line too long (84 > 80 characters)  (line-length)
  48:81     error    line too long (117 > 80 characters)  (line-length)
  59:3      error    wrong indentation: expected 4 but found 2  (indentation)
  64:3      error    wrong indentation: expected 4 but found 2  (indentation)
  65:5      error    wrong indentation: expected 6 but found 4  (indentation)
  72:5      error    wrong indentation: expected 6 but found 4  (indentation)
  74:81     error    line too long (148 > 80 characters)  (line-length)
  78:5      error    wrong indentation: expected 6 but found 4  (indentation)
  82:5      error    wrong indentation: expected 6 but found 4  (indentation)
  96:5      error    wrong indentation: expected 6 but found 4  (indentation)
  102:5     error    wrong indentation: expected 6 but found 4  (indentation)
  116:5     error    wrong indentation: expected 6 but found 4  (indentation)
  124:81    error    line too long (89 > 80 characters)  (line-length)
  130:81    error    line too long (84 > 80 characters)  (line-length)
  135:3     error    wrong indentation: expected 4 but found 2  (indentation)
  143:7     error    wrong indentation: expected 8 but found 6  (indentation)
  146:3     error    wrong indentation: expected 4 but found 2  (indentation)
  156:3     error    wrong indentation: expected 4 but found 2  (indentation)
  163:3     error    wrong indentation: expected 4 but found 2  (indentation)
  165:3     error    wrong indentation: expected 4 but found 2  (indentation)
  167:5     error    wrong indentation: expected 6 but found 4  (indentation)
  184:5     error    wrong indentation: expected 6 but found 4  (indentation)
  195:5     error    wrong indentation: expected 6 but found 4  (indentation)
  198:5     error    wrong indentation: expected 6 but found 4  (indentation)

```

**Comment by simonbaird** [comment]
I can make pipeline-quay-demo.yaml valid with some .yamllint config related to indentation.

Not sure what's best, but maybe this:

    indentation: {spaces: 2, indent-sequences: consistent}

https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.indentation

**Comment by simonbaird** [comment]
Not sure why but it seems to not be working for me. Something to do with the path and the current directory.

```
localhost:~/code/infra-deployments/hack/chains> [HACBS-45] yamllint .
./zzz.yaml
  8:121     warning  line too long (1945 > 120 characters)  (line-length)
  120:121   warning  line too long (125 > 120 characters)  (line-length)

./zz.yaml
  10:3      warning  wrong indentation: expected 4 but found 2  (indentation)
  11:5      warning  wrong indentation: expected 6 but found 4  (indentation)
  16:5      warning  wrong indentation: expected 6 but found 4  (indentation)

localhost:~/code/infra-deployments/hack/chains> [HACBS-45] ./check-yaml.sh 
[Errno 2] No such file or directory: 'hack/chains/zz.yaml'
[Errno 2] No such file or directory: 'hack/chains/zzz.yaml'

YAML Validation failed
```

Also, I'm not sure if we need to do all that work in bash. Does yamllint by itself work pretty much the same? E.g. `yamllint <filename>` or `yamllint .`

**Comment by simonbaird** [comment]
LGTM. Are you happy to merge?

**Pull request merged**
