### PR TITLE
add note to access ArgoCD for user workloads

### PR DESCRIPTION
**Pull request by scoheb**

### CODE REVIEW

**Comment by scoheb** [comment]
FYI @jgwest

**Review by Michkov — APPROVED** [review]

**Comment by jgwest** [comment]
My understanding is that `appstudio-e2e-deployment` currently won't run for `README.md` only changes, so I am merging w/o the test result.

**Comment by jgwest** [comment]
My understanding is that `appstudio-e2e-deployment` currently won't run for `README.md` only changes, so I am merging w/o the test result.

**Pull request merged**
