### PR TITLE
Fix tekton-chains resource limits and set a new signing-secret

### PR DESCRIPTION
**Pull request by Mo3m3n**

### CODE REVIEW

**Review by ramessesii2 — APPROVED** [review]

**Review by Michkov — APPROVED** [review]

**Comment by scoheb** [comment]
Changing the tekton chains secret will cause other services to fail without rotating the pub secret. Can you please announce this on slack?

**Comment by Michkov** [comment]
@scoheb yop, planned. Basically old key was lost with https://github.com/redhat-appstudio/infra-deployments/pull/982

**Comment by Mo3m3n** [comment]
old keys were lost before https://github.com/redhat-appstudio/infra-deployments/pull/982, however redeploying the controller made the issue visible and there was no backup of the old keys. New keys have now a backup copy.

**Pull request merged**
