### PR TITLE
Fixed some wording, grouped access info together

### PR DESCRIPTION
**Pull request by amfred**
Also includes what's in https://github.com/redhat-appstudio/infra-deployments/pull/718/

### CODE REVIEW

**Review by Michkov — APPROVED** [review]

**Comment by amfred** [comment]
/unhold
I'm curious how this might work (or not)

**Comment by amfred** [comment]
I'm curious if that unhold will make Tide merge this?

**Comment by amfred** [comment]
It did auto-merge.  Cool.

**Pull request merged**
