### PR TITLE
Add Tempo operator to enable viewing traces in development environment

### PR DESCRIPTION
**Pull request by raks-tt**
The Tempo operator exposes the Jaeger UI, enabling the viewing of traces exclusively in the development environment.

Tested the traces:
image

### CODE REVIEW

**Review by mftb — APPROVED** [review]
/lgtm
/approve

**Review by pavolloffay — APPROVED** [review]

**Comment by arewm** [comment]
I am not sure that I am the best person to review this PR. @gbenhaim or @hugares, do you know who might be better to review it?

**Comment by hugares** [comment]
> I am not sure that I am the best person to review this PR. @gbenhaim or @hugares, do you know who might be better to review it?

Either one of us :) Let me have a look

**Review by hugares — APPROVED** [review]
/lgtm

**Pull request merged**
