### PR TITLE
KFLUXBUGS-1610 - Update logging operator to 6.0.2. to pick up changes…

### PR DESCRIPTION
**Pull request by mike-kingsbury**
… to better troubleshoot long log lines being dropped.

Documentation used:
https://docs.openshift.com/container-platform/4.16/observability/logging/logging-6.0/log6x-upgrading-to-6.html
https://github.com/openshift/cluster-logging-operator/blob/master/docs/administration/upgrade/v6.0_changes.adoc
...
and many oc explain clusterlogforwarders.observability.openshift.io.spec... commands.

TL;DR: clusterlogging.logging.openshift.io and clusterlogforwarder.logging.openshift.io were combined into clusterlogforwarder.observability.openshift.io. Filters got pulled out into their own section, details about the outputs also pulled into an object named after the output type.

### CODE REVIEW

**Comment by mftb** [comment]
@hugares @ifireball PTAL

**Review by hugares — APPROVED** [review]
/lgtm
/hold

**Comment by hugares** [comment]
@mike-kingsbury I approved the PR, remove the hold label when you are ready to merge it

**Review by mftb — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
