### PR TITLE
Group konflux-ci/tekton-catalog updates

### PR DESCRIPTION
**Pull request by staticf0x**
This update will allow noise reduction by grouping `quay.io/konflux-ci/tekton-catalog/*` tekton updates into a single PR.

### CODE REVIEW

**Comment by staticf0x** [comment]
@gnaponie do you know why is there both `matchPackagePatterns` and `matchDepPatterns`?

**Review by qixiang — APPROVED** [review]
/lgtm
/approve

**Comment by gnaponie** [comment]
@staticf0x check this out: https://github.com/renovatebot/renovate/discussions/14885
I think we should drop matchPackagePatterns. I think it's coming from the old build-service's renovate, I believe we can remove that.
I was actually thinking about filing a card about clearing this conf a little bit, because it comes with a lot of warnings. We can include this too in that card (since this was approved, and it will be merged once the CI completes).

**Review by gnaponie — APPROVED** [review]

**Comment by staticf0x** [comment]
What does it take to run the rest of the checks?

**Comment by qixiang** [comment]
Hi @scoheb do you know what is missing to trigger the remaining tests or allow this PR to proceed?

**Review by gnaponie — APPROVED** [review]

**Review by gnaponie — APPROVED** [review]

**Pull request closed without merging**
