### PR TITLE
doc: how to add a new grafana dashboard

### PR DESCRIPTION
**Pull request by skabashnyuk**
Instruction how to add new grafana dashboard

### CODE REVIEW

**Review by xcoulon — APPROVED** [review]

**Comment by scoheb** [comment]
> Should I include a note about how to update a reference to the dashboard in tekton task? For example https://github.com/redhat-appstudio/service-provider-integration-operator/blob/02c2b7042a1b8cfff1fc489a964cc3142bcefcbe/.tekton/controller-push.yaml#L28

I would. It is handy

**Review by bamachrn — CHANGES_REQUESTED** [review]
could we move this doc to the onboarding doc https://github.com/redhat-appstudio/infra-deployments/blob/main/components/monitoring/README.md on section 4?
this will make sure all the onboarding doc are in same place.

https://github.com/redhat-appstudio/infra-deployments/tree/main/components/monitoring/grafana/README.md this readme is meant for setting up grafana service itself

**Review by bamachrn — APPROVED** [review]
Looks good to me

**Pull request merged**
