### PR TITLE
Revert "Bump pipeline-service version"

### PR DESCRIPTION
**Pull request by enarha**
Reverts redhat-appstudio/infra-deployments#1592

### CODE REVIEW

**Comment by gabemontero** [comment]
only 1 commit / no ec changes @enarha @Roming22 @adambkaplan  :-) 

/lgtm

**Review by flacatus — APPROVED** [review]

**Comment by flacatus** [comment]
Devfile problem is solved, but seems we have another problem with jvm and sla… cc @psturc @Dannyb48

**Comment by gabemontero** [comment]
tests passed
```
 INFO[2023-04-04T20:53:44Z] Running multi-stage phase test               
INFO[2023-04-04T20:53:44Z] Running step appstudio-e2e-tests-redhat-appstudio-e2e. 
INFO[2023-04-04T21:18:45Z] Step appstudio-e2e-tests-redhat-appstudio-e2e succeeded after 25m0s. 
INFO[2023-04-04T21:18:45Z] Step phase test succeeded after 25m0s.       
```
will wait for tide to handle merge

**Pull request merged**
