### PR TITLE
Enable deep-inspection for Chains in tekton config

### PR DESCRIPTION
**Pull request by gabemontero**
to test the konflux e2e's against https://github.com/openshift-pipelines/pipeline-service/pull/985 before merging https://github.com/openshift-pipelines/pipeline-service/pull/985

@yashvardhannanavati @arewm @lcarva fyi

turns out after initially opening this as a test feature, the easier debug we  get with infra-deployment e2e's allowed us to determine that string  vs. bool for the field being set had bearing with the operator

 see https://github.com/redhat-appstudio/infra-deployments/pull/3543#issuecomment-2040315963

also, as part of our (well mine minimally, but I think there is a consensus) overall intent to start moving off of pipeline service for config changes, I actually want to limit the update to this repo vs updating pipeline-service

rh-pre-commit.version: 2.2.0
rh-pre-commit.check-secrets: ENABLED

### CODE REVIEW

**Comment by gabemontero** [comment]
yeah my test PR here is somehow off @yashvardhannanavati and the gitops deployment for pipeline service is failing in https://prow.ci.openshift.org/view/gs/test-platform-results/pr-logs/pull/redhat-appstudio_infra-deployments/3543/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1775978150711267328 

we'll have to circle back to this once you get https://github.com/openshift-pipelines/pipeline-service/pull/985 at least passing the smoke test

**Comment by gabemontero** [comment]
@yashvardhannanavati I brought up this branch on a local cluster and was able to see why the pipeline service is not coming up

Gitops cannot fully sync the TektonConfig.

Now, your branch https://github.com/yashvardhannanavati/pipeline-service/tree/enable_deep_inspect is up to date wrt main branch, so it is not that.

I suspect we are hitting one of the unfortunate difficulties with managing tekton with both the operator and gitops.  They sometimes want to update things like the tekton config object concurrently, and they wipe out each other's updates.

Multiple writers scenario.  We have hit this on occasion.

To see about resolving this, I'm going to create an alternative to https://github.com/openshift-pipelines/pipeline-service/pull/985 that exposes `artifacts.pipelinerun.enable-deep-inspection` but sets it to / leaves it `false`.

I'll then update this PR to point to my branch, but also patch the tekton config to set `artifacts.pipelinerun.enable-deep-inspection`  to `true`

Hopefully that solves it.  Otherwise, we end up in having to deal with sync-waves hell, or I have to look at the diffs between desired and live manifests for the `TektonConfig` 

Possible nice side effect:  if I get this sorted and the e2e's pass, you don't have to worry about getting the chains smoke test in the pipeline-service PR working again.

@arewm @lcarva FYI

**Comment by gabemontero** [comment]
> @yashvardhannanavati I brought up this branch on a local cluster and was able to see why the pipeline service is not coming up
> 
> Gitops cannot fully sync the TektonConfig.
> 
> Now, your branch https://github.com/yashvardhannanavati/pipeline-service/tree/enable_deep_inspect is up to date wrt main branch, so it is not that.
> 
> I suspect we are hitting one of the unfortunate difficulties with managing tekton with both the operator and gitops. They sometimes want to update things like the tekton config object concurrently, and they wipe out each other's updates.
> 
> Multiple writers scenario. We have hit this on occasion.
> 
> To see about resolving this, I'm going to create an alternative to [openshift-pipelines/pipeline-service#985](https://github.com/openshift-pipelines/pipeline-service/pull/985) that exposes `artifacts.pipelinerun.enable-deep-inspection` but sets it to / leaves it `false`.
> 
> I'll then update this PR to point to my branch, but also patch the tekton config to set `artifacts.pipelinerun.enable-deep-inspection` to `true`
> 
> Hopefully that solves it. Otherwise, we end up in having to deal with sync-waves hell, or I have to look at the diffs between desired and live manifests for the `TektonConfig`
> 
> Possible nice side effect: if I get this sorted and the e2e's pass, you don't have to worry about getting the chains smoke test in the pipeline-service PR working again.
> 
> @arewm @lcarva FYI

actually now as I look at it, it may be better @yashvardhannanavati  to pivot back to a infra-deployments only patch on the TektonConfig

I'll work it up and see.

@enarha FYI

**Comment by lcarva** [comment]
```
cannot decode incoming new object: json: cannot unmarshal string into Go struct field
Chain.spec.chain.artifacts.pipelinerun.enable-deep-inspection of type bool
```

The changes in this PR do set `artifacts.pipelinerun.enable-deep-inspection` to the string `"true"`. There's probably a bug somewhere along the way that is converting the string `"true"` to the boolean `true`.

The Tekton Chains config ConfigMap expects that value to be of type string. But the operator [expects](https://github.com/tektoncd/operator/blob/7bc7f7eb4a5b327a9c66929c6a89974fab85de75/pkg/apis/operator/v1alpha1/tektonchain_types.go#L86) it to be a boolean.

There's another config attribute for Chains that is a boolean-wrapped-in-a-string, `transparency.enabled`. In the operator that is handled as a [BoolValue](https://github.com/tektoncd/operator/blob/7bc7f7eb4a5b327a9c66929c6a89974fab85de75/pkg/apis/operator/v1alpha1/tektonchain_types.go#L123C45-L123C65). I'm not too familiar with the operator code, but it sounds like the `BoolValue` should also be used [here](https://github.com/tektoncd/operator/blob/7bc7f7eb4a5b327a9c66929c6a89974fab85de75/pkg/apis/operator/v1alpha1/tektonchain_types.go#L86).

**Comment by gabemontero** [comment]
> ```
> cannot decode incoming new object: json: cannot unmarshal string into Go struct field
> Chain.spec.chain.artifacts.pipelinerun.enable-deep-inspection of type bool
> ```
> 
> The changes in this PR do set `artifacts.pipelinerun.enable-deep-inspection` to the string `"true"`. There's probably a bug somewhere along the way that is converting the string `"true"` to the boolean `true`.
> 
> The Tekton Chains config ConfigMap expects that value to be of type string. But the operator [expects](https://github.com/tektoncd/operator/blob/7bc7f7eb4a5b327a9c66929c6a89974fab85de75/pkg/apis/operator/v1alpha1/tektonchain_types.go#L86) it to be a boolean.
> 
> There's another config attribute for Chains that is a boolean-wrapped-in-a-string, `transparency.enabled`. In the operator that is handled as a [BoolValue](https://github.com/tektoncd/operator/blob/7bc7f7eb4a5b327a9c66929c6a89974fab85de75/pkg/apis/operator/v1alpha1/tektonchain_types.go#L123C45-L123C65). I'm not too familiar with the operator code, but it sounds like the `BoolValue` should also be used [here](https://github.com/tektoncd/operator/blob/7bc7f7eb4a5b327a9c66929c6a89974fab85de75/pkg/apis/operator/v1alpha1/tektonchain_types.go#L86).

conceivably yeah @lcarva could be that too ... though it is curious that  a few lines down

`transparency.enabled: "false"` 

works fine

also from @yashvardhannanavati  's PR https://github.com/openshift-pipelines/pipeline-service/pull/985 if you look at https://github.com/openshift-pipelines/pipeline-service/pull/985/files#diff-7b0f46511f3c76f0deb347cc69126f54ac59102bee06eeee07471cf9fa02b8bdR48 the `"false"` was used.
First, maybe that should have been `"true"` ?
next, it is in quotes 

maybe the supposed bug varies on true vs. false

I'll experiment some more with this PR and see what varying results occur

**Comment by gabemontero** [comment]
I also know next to little about the operator code but your find on the different fields and Bool vs. BoolValue does seem relevant @lcarva 

In the interim, I'm trying with true, no quotes,  to see if the operator does the right thing with the config map

**Comment by yashvardhannanavati** [comment]
@gabemontero I had temporarily changed it to "false" to check if it's indeed the config change causing the issue. I see Lui's comment now.

**Comment by gabemontero** [comment]
any sense @lcarva @yashvardhannanavati if this one failure:
```
 • [FAILED] [3.916 seconds]
[rhtap-demo-suite] DEVHAS-337: creates quarkus application from a private repository which contain a devfile [It] creates an application [rhtap-demo, verify-stage]
/tmp/tmp.KYKPiE6uY5/tests/rhtap-demo/rhtap-demo.go:174
  Timeline >>
  Waiting for UserSignup rhtap-demo-pyzb to have condition Complete:True
  Waiting for UserSignup rhtap-demo-pyzb to have condition Complete:True
  Waiting for UserSignup rhtap-demo-pyzb to have condition Complete:True
  Waiting for UserSignup rhtap-demo-pyzb to have condition Complete:True
  Parallel processes: 15
  Running on namespace: rhtap-demo-pyzb-tenant
  User: rhtap-demo-pyzb
  Parallel process 14
  [FAILED] in [It] - /tmp/tmp.KYKPiE6uY5/tests/rhtap-demo/rhtap-demo.go:177 @ 04/05/24 18:10:02.805
  test: rhtap-demo, namespace: rhtap-demo-pyzb-tenant, resourceQuota: appstudio-crds-spi, resource: count/spiaccesschecks.appstudio.redhat.com, available: 512, used: 0
  test: rhtap-demo, namespace: rhtap-demo-pyzb-tenant, resourceQuota: appstudio-crds-spi, resource: count/spiaccesstokenbindings.appstudio.redhat.com, available: 512, used: 0
  test: rhtap-demo, namespace: rhtap-demo-pyzb-tenant, resourceQuota: appstudio-crds-spi, resource: count/spiaccesstokendataupdates.appstudio.redhat.com, available: 512, used: 0
  test: rhtap-demo, namespace: rhtap-demo-pyzb-tenant, resourceQuota: appstudio-crds-spi, resource: count/spiaccesstokens.appstudio.redhat.com, available: 512, used: 0
  test: rhtap-demo, namespace: rhtap-demo-pyzb-tenant, resourceQuota: appstudio-crds-spi, resource: count/spifilecontentrequests.appstudio.redhat.com, available: 512, used: 0
  << Timeline
  [FAILED] Unexpected error:
      <*url.Error | 0xc001909d10>: 
      Post "https://api-toolchain-host-operator.apps.rhtap-4-14-us-east-2-trf94.ci.stonesoupengineering.com/apis/appstudio.redhat.com/v1alpha1/namespaces/rhtap-demo-pyzb-tenant/applications": EOF
      {
          Op: "Post",
          URL: "https://api-toolchain-host-operator.apps.rhtap-4-14-us-east-2-trf94.ci.stonesoupengineering.com/apis/appstudio.redhat.com/v1alpha1/namespaces/rhtap-demo-pyzb-tenant/applications",
          Err: <*errors.errorString | 0xc0000c6120>{s: "EOF"},
      }
  occurred
  In [It] at: /tmp/tmp.KYKPiE6uY5/tests/rhtap-demo/rhtap-demo.go:177 @ 04/05/24 18:10:02.805 
```

from the 4-14 test is at all chains related ?

**Comment by gabemontero** [comment]
/hold 

per slack conversation @lcarva and @yashvardhannanavati are going to do some additional testing in one of their clusters, and if that is successful, then we'll move forward in stage.

you guys can remove the hold and tag with lgtm when you think this is ready.

**Comment by yashvardhannanavati** [comment]
lgtm

**Comment by gabemontero** [comment]
@yashvardhannanavati you need to put a slash character before the lgtm if you want the label applied

I applied the label for you in the interim.

**Review by enarha — APPROVED** [review]

**Comment by enarha** [comment]
@gabemontero @yashvardhannanavati unless we can force merge this change, I've cherry-picked the commit and opened https://github.com/redhat-appstudio/infra-deployments/pull/3580 to work around the "pending for approval" issue.

**Comment by gabemontero** [comment]
closing in favor of @enarha 's PR https://github.com/redhat-appstudio/infra-deployments/pull/3580

**Pull request closed without merging**
