### PR TITLE
remove workspaces from production clusters

### PR DESCRIPTION
**Pull request by sadlerap**
With the decision from upstream Konflux to not pursue a workspaces abstraction, it doesn't make sense to have workspaces deployed to the production clusters.  Staging will be removed once all of the dependencies on workspaces that exist there (UI) have been changed to no longer depend on workspaces.

### CODE REVIEW

**Comment by hugares** [comment]
We are sure that the current UI, both for external cluster(hosted on consoledot) and for internal cluster(hosted in the konflux cluster) do not have any dependency on the workspaces?

**Comment by sadlerap** [comment]
I don't believe so, but it'd be good to get confirmation from the UI team just to be sure.

**Comment by hugares** [comment]
> We are sure that the current UI, both for external cluster(hosted on consoledot) and for internal cluster(hosted in the konflux cluster) do not have any dependency on the workspaces?

@sahil143 Can you confirm?

**Review by hugares — APPROVED** [review]

**Comment by sahil143** [comment]
> > We are sure that the current UI, both for external cluster(hosted on consoledot) and for internal cluster(hosted in the konflux cluster) do not have any dependency on the workspaces?
> 
> @sahil143 Can you confirm?

Yes, We do not use the workspaces api.

**Pull request merged**
