### PR TITLE
Fix(RHTAPWATCH-332): Remove the o11y component from infra-deployments

### PR DESCRIPTION
**Pull request by Kousalya1998**
- Remove o11y components and references from infra-deployments

### CODE REVIEW

**Comment by yftacherzog** [comment]
@Kousalya1998 
Did you deploy it in dev and made sure all apps are able to converge (not in degraded/progressing, etc.)?
Did you run `kustomize build` for the production and staging clusters to see that it runs correctly?

**Comment by hmariset** [comment]
LGTM.
Tested along with @Kousalya1998 in dev environment and all apps are Synced and Healthy.

**Review by hmariset — APPROVED** [review]

**Review by amisstea — APPROVED** [review]

**Comment by yftacherzog** [comment]
> LGTM. Tested along with @Kousalya1998 in dev environment and all apps are Synced and Healthy.

@hmariset did you also test that `kustomize build` runs correctly for the production and staging clusters?

**Comment by Kousalya1998** [comment]
@yftacherzog I checked `kustomize build` for two Kustomization files and it doesn't have `o11y` keyword in it.

**Comment by hmariset** [comment]
> > LGTM. Tested along with @Kousalya1998 in dev environment and all apps are Synced and Healthy.
> 
> @hmariset did you also test that `kustomize build` runs correctly for the production and staging clusters?

Yes Yftach, we have run `kustomize build` and it works correctly for production and staging clusters.

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
