### PR TITLE
Update pipeline-service in development/staging

### PR DESCRIPTION
**Pull request by Roming22**
* Create `pipelines-scc` SecurityContextConstraint via ArgoCD.
* Disable the pipeline service account
  * Turn off creation of RBAC resources
  * Add job to create the service certificate authority for Chains, which was provided by the OpenShift Pipelines Operator RBAC feature (not documented!)
* Disable image signing test

### CODE REVIEW

**Comment by adambkaplan** [comment]
/hold

I have a few concerns:

- Image signing test is disabled, this means we are not verifying that chains is working properly end to end.
- We are using a job to re-create the ca-bundle for chains to access the internal registry (I believe this is why we need it?). This might be prone to a race condition between the operator and ArgoCD.

**Comment by Roming22** [comment]
@adambkaplan 
1. The test was deactivated in pipeline-service, but my understanding is that [there is a test](https://github.com/redhat-appstudio/e2e-tests/blob/8578eca880ec8f692d0463b7f42e1b1e884a083b/tests/build/chains.go#L61) in the e2e suite.
2. Is it that the job might be run before the old cabundle has been deleted? Could it be solved by moving the job to another sync-wave, or do we have to be smarter about it?

**Comment by Roming22** [comment]
@adambkaplan I've opened https://github.com/openshift-pipelines/pipeline-service/pull/645 to address #2.

**Review by gabemontero — APPROVED** [review]
/lgtm

**Pull request merged**
