### PR TITLE
move sandbox-sre-admin RBAC to sandbox component

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Review by alexeykazakov — APPROVED** [review]

**Comment by Michkov** [comment]
This is failing because it's applying ClusterRoles from sandbox-sre-admins.yaml on member and host operator. That's causing conflict since both of them are on the same cluster. Possible solution is to create development overlay which will not apply the RBAC or it will be applying it only on eg. member operator.

**Comment by mfrancisc** [comment]
@Michkov thanks for your suggestion. Could you please take a look at https://github.com/redhat-appstudio/infra-deployments/pull/2284 , If I'm not missing something this should apply the ClusterRole only on member-operator cluster when in development mode (which is the same as host operator cluster).

**Comment by mfrancisc** [comment]
@MatousJobanek the changes got merged with https://github.com/redhat-appstudio/infra-deployments/pull/2284 , I think we can close this one.

**Comment by MatousJobanek** [comment]
@mfrancisc thanks for taking care of it :pray: 
closing in favor of https://github.com/redhat-appstudio/infra-deployments/pull/2284

**Pull request closed without merging**
