### PR TITLE
Update Pipeline Service in Staging

### PR DESCRIPTION
**Pull request by sayan-biswas**
* Bump metrics exporter through noncaching client change
* Update tekton results
* Increase log buffer size in tekton results
* Update pipeline service exporter image path

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by xinredhat** [comment]
Hit issue https://issues.redhat.com/browse/RHTAPBUGS-101

**Comment by gabemontero** [comment]
@sayan-biswas @Roming22 looking at the last e2e test failure:

```
 Summarizing 1 Failure:
  [FAIL] [mvp-demo-suite MVP Demo tests] MVP Demo Chapter 2 - advanced pipeline, JVM rebuild, successful release [It] merging the PaC init branch eventually leads to triggering another PipelineRun [mvp-demo, mvp-demo-chapter-2]
  /tmp/tmp.m1pCNPuhBd/tests/mvp-demo/mvp-demo.go:438
```

it has been our recent experience that test failing has often been the result of a PaC version change.  I'll triage the last run a bit while the current one is going on to see if I can discern if that was the case again.

**Comment by gabemontero** [comment]
The bug is https://issues.redhat.com/browse/SRVKP-3134 and yep it is the same stack trace.

@chmouel - I think it is time to try out that theory / fix you alluded to in https://redhat-internal.slack.com/archives/CG5GV6CJD/p1685110454197389?thread_ts=1685108707.222059&cid=CG5GV6CJD as setting up a non-CI reproducer of the SIGSEGV between you, Savita, and @psturc proved difficult

**Comment by gabemontero** [comment]
I will see about submitting a minimal PR so we can at least get past this SIGSEGV and get a useful error log @chmouel @savitaashture @sayan-biswas @Roming22

**Comment by chmouel** [comment]
sorry i replied on the jira ticket but that may be a more convenient place to discuss here

maybe some other things, what about increasing the https://github.com/openshift-pipelines/pipelines-as-code/blob/933d200e3c867a024ec90fcd108c8725bea383d6/pkg/kubeinteraction/secrets.go#L45 retry value in there.

it should not sigsev but if we can't patch the pipelinerun annotations and adding the installationid some other stuff are going to break (the reconciler/watcher)

**Comment by gabemontero** [comment]
ok https://github.com/openshift-pipelines/pipelines-as-code/pull/1309 is up

once @chmouel is happy with merging it, we'll cherrypick to 0.17.x and cut a 0.17.4 release 

we'll then need to update pipeline-service @Roming22 @sayan-biswas to pick that up.  Then redo this PR to point to that commit.

**Comment by sayan-biswas** [comment]
I will update this PR once [#1309](https://github.com/openshift-pipelines/pipelines-as-code/pull/1309) change is synced with pipeline-service.

**Pull request merged**
