### PR TITLE
Update pipeline-service

### PR DESCRIPTION
**Pull request by Roming22**
* Deploy downstream images for pipelines-as-code and tekton-chains (ESS remediation).

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]

**Comment by Michkov** [comment]
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1776/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1653861200703787008/artifacts/appstudio-e2e-tests/redhat-appstudio-hypershift-gather/artifacts/pods/pipelines-as-code_pipelines-as-code-controller-6f6d6464d7-2qhtv_pac-controller.log 
`{"severity":"ERROR","timestamp":"2023-05-03T21:15:52.898049112Z","logger":"pipelinesascode","caller":"events/emit.go:45","message":"PipelineRun test-mvp-component-ccge-on-pull-request- has failed: creating pipelinerun test-mvp-component-ccge-on-pull-request- in mvp-demo-dev-namespace-voky-tenant has failed: admission webhook \"validation.webhook.pipeline.tekton.dev\" denied the request: validation failed: must not set the field(s): spec.pipelineSpec.finally[0].taskref.params, spec.pipelineSpec.finally[0].taskref.resolver, spec.pipelineSpec.finally[1].taskref.params, spec.pipelineSpec.finally[1].taskref.resolver, spec.pipelineSpec.tasks[0].taskref.params, spec.pipelineSpec.tasks[0].taskref.resolver, spec.pipelineSpec.tasks[10].taskref.params, spec.pipelineSpec.tasks[10].taskref.resolver, spec.pipelineSpec.tasks[11].taskref.params, spec.pipelineSpec.tasks[11].taskref.resolver, spec.pipelineSpec.tasks[1].taskref.params, spec.pipelineSpec.tasks[1].taskref.resolver, spec.pipelineSpec.tasks[2].taskref.params, spec.pipelineSpec.tasks[2].taskref.resolver, spec.pipelineSpec.tasks[3].taskref.params, spec.pipelineSpec.tasks[3].taskref.resolver, spec.pipelineSpec.tasks[4].taskref.params, spec.pipelineSpec.tasks[4].taskref.resolver, spec.pipelineSpec.tasks[5].taskref.params, spec.pipelineSpec.tasks[5].taskref.resolver, spec.pipelineSpec.tasks[6].taskref.params, spec.pipelineSpec.tasks[6].taskref.resolver, spec.pipelineSpec.tasks[7].taskref.params, spec.pipelineSpec.tasks[7].taskref.resolver, spec.pipelineSpec.tasks[8].taskref.params, spec.pipelineSpec.tasks[8].taskref.resolver, spec.pipelineSpec.tasks[9].taskref.params, spec.pipelineSpec.tasks[9].taskref.resolver ","provider":"github","event-id":"ae8d6790-e9f7-11ed-93e7-655633528013","event-sha":"bdf50475e733ecec924661cfedf70f5f3f89c38a","event-type":"pull_request","stacktrace":"github.com/openshift-pipelines/pipelines-as-code/pkg/events.(*EventEmitter).EmitMessage\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/pkg/events/emit.go:45\ngithub.com/openshift-pipelines/pipelines-as-code/pkg/pipelineascode.(*PacRun).Run.func1\n\t/go/src/github.com/openshift-pipelines/pipelines-as-code/pkg/pipelineascode/pipelineascode.go:79"}`

The pull-request which failed -> https://github.com/redhat-appstudio-qe/hacbs-test-project/pull/1732/ , that's pipelineRun in v1beta1 version which is working without issue with older pipeline-as-code.

**Review by gabemontero — APPROVED** [review]
/lgtm

**Comment by gabemontero** [comment]
mvp demo failed yet again @Roming22 (along with some other failures I'm classifying as flakes for now since we have not seen them previously)

```
 • [FAILED] [900.904 seconds]
[mvp-demo-suite MVP Demo tests] MVP Demo Chapter 2 - advanced pipeline, JVM rebuild, successful release [It] Release PipelineRun should eventually succeed and associated Release should be marked as succeeded [mvp-demo, mvp-demo-chapter-2]
/tmp/tmp.XwZZzgNqEA/tests/mvp-demo/mvp-demo.go:450
```

per slack/standup discussions, I'm trying to repo locally to confirm / facilitate debug.
I'll also try mvp-demo against main branch to confirm/deny if the failure is happening there.

**Comment by gabemontero** [comment]
test has started in https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1776/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1656761058292928512 so we'll need at least 1 more retest after this current run fails

**Comment by gabemontero** [comment]
I'll rebase / retest if https://github.com/redhat-appstudio/e2e-tests/pull/515 merges

**Comment by ramessesii2** [comment]
Closing in favor of https://github.com/redhat-appstudio/infra-deployments/pull/1811

**Comment by gabemontero** [comment]
Just to be clear, #1811 is bringing the change in default tekton SA's, and for now is skipping the switch from the upstream to downstream images for chains and PaC.

Both goals are still needed sooner rather than later.  Hopefully we can sort out the EC related changes need to make the downstream images work in e2e's in parallel, and then pivot right back to using the downstream images after #1811 merges.

**Pull request closed without merging**
