### PR TITLE
STONEBLD-1844 testing do not merge

### PR DESCRIPTION
**Pull request by stuartwdouglas**

### CODE REVIEW

**Comment by dheerajodha** [comment]
looking at the failures :eyes:

**Comment by stuartwdouglas** [comment]
This PR is very much WIP.

**Comment by dheerajodha** [comment]
Oh I see, few of these failures are related to your test that's failing [here](https://github.com/redhat-appstudio/e2e-tests/pull/904/files#diff-938ddf0d569d68c3df496d8b4065614ff56cc303c33555755621cffcec97ef74R1393).


btw if I understand correctly, you want to run your tests on a given image. If you don't know this already, there's a quicker way to do this though, you can export these two variables within the .env file ([like this](https://github.com/redhat-appstudio/e2e-tests/blob/main/default.env)):
```
export BUILD_SERVICE_IMAGE_REPO=quay.io/redhat-appstudio/pull-request-builds
export BUILD_SERVICE_IMAGE_TAG=buildserv-ee99cf892414dbf82c8e1f859a7a2da6725438a5
```
and follow the steps mentioned in [this guide](https://github.com/redhat-appstudio/e2e-tests/blob/main/docs/Installation.md#rhtap-in-dev-mode) -- although I agree the setup is not "quick" if you're trying it for the first time, I did a presentation on it somewhere, let me know if you need help with that.

If you already know about this, then please ignore my message.

**Pull request closed without merging**
