### PR TITLE
Update gitops component

### PR DESCRIPTION
**Pull request by jgwest**

### CODE REVIEW

**Comment by Michkov** [comment]
@jgwest I deployed system with the change, when I created application/component for first time then it created successfully the application in gitops-service-argocd. But then when I tried to run e2e tests the application was not created. I was able to see that I have gitopsdeployments.managed-gitops.redhat.com in the test namespace:
```
$ oc get gitopsdeployments.managed-gitops.redhat.com
NAME                         AGE
gitops-deployment-e2e625cx   56m
gitops-deployment-e2ex9bnh   19m
$ oc get -o yaml gitopsdeployments.managed-gitops.redhat.com gitops-deployment-e2ex9bnh
apiVersion: managed-gitops.redhat.com/v1alpha1
kind: GitOpsDeployment
metadata:
  creationTimestamp: "2022-07-27T10:12:15Z"
  generateName: gitops-deployment-e2e
  generation: 1
  name: gitops-deployment-e2ex9bnh
  namespace: appstudio-e2e-test
  resourceVersion: "128129"
  uid: af5c1aa1-9564-4820-983e-c4d6bd27f8ae
spec:
  destination: {}
  source:
    path: components/nodejs-component/base
    repoURL: https://github.com/Michkov-test/e2e-nodejs-appstudio-e2e-test-reject-attend
    targetRevision: main
  type: automated
$
```
I tried to delete them:
```
$ oc delete gitopsdeployments.managed-gitops.redhat.com --all
gitopsdeployment.managed-gitops.redhat.com "gitops-deployment-e2e625cx" deleted
gitopsdeployment.managed-gitops.redhat.com "gitops-deployment-e2ex9bnh" deleted
$
```
But it also deleted applications in `openshift-gitops` which completely destroyed my cluster.

**Comment by Michkov** [comment]
Another try:
now I deployed and run `./bin/e2e-appstudio --ginkgo.focus="e2e-demos-suite"`:
For each appstudio application it created second Argocd application after pipeline was executed.
image
Difference between that two is Target Revision (one is empty and one is `main`) and Path (one is `./` and second `components/component-golang/base`)
And there are shared resource warnings.

The test passed, but after cleanup (removal of components/applications) I can see argocd applications with path `components/component-golang/base` and revision `main` with comparisonError -> `rpc error: code = Unknown desc = authentication required` since the git repo was already removed.

**Comment by jgwest** [comment]
@Michkov :thinking:

**Comment by jgwest** [comment]
Related fixes: https://github.com/redhat-appstudio/managed-gitops/pull/186

**Pull request merged**
