### PR TITLE
Update ClusterLogging CR collection spec

### PR DESCRIPTION
**Pull request by eisraeli**
Update the 'ClusterLogging' CR collection spec
according to the updated spec as documented here:
https://docs.openshift.com/container-platform/4.16/observability/logging/log_collection_forwarding/cluster-logging-collector.html#configuring-logging-collector_cluster-logging-collector

### CODE REVIEW

**Review by hugares — APPROVED** [review]
/lgtm

**Review by amisstea — APPROVED** [review]
/lgtm

**Review by yftacherzog — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
