### PR TITLE
Update pipeline-service in production

### PR DESCRIPTION
**Pull request by Roming22**
* Added overlay for the performance settings so that default settings
  are used in production until we are ready to activate tuned settings
* Rename pipelines-scc to appstudio-pipelines-scc
* Update pipeline-service-exporter-reader ClusterRole to watch
  pipelineruns and task runs, and get customresourcedefinitions
* Align Pipelines Controller logs with [ADR-6](https://issues.redhat.com//browse/ADR-6)
* Use downstream image for tekton chains
* Add more ArgoCD sync-wave and phases
* Set 'enable-api-fields: beta' in OSP

### CODE REVIEW

**Review by gabemontero — APPROVED** [review]
/lgtm

**Review by adambkaplan — CHANGES_REQUESTED** [review]
@Roming22 please provide the following in the commit message body (and pull request description):

1. Which features are being promoted to production by this change?
2. Why are we providing an overlay for performance settings?

**Comment by gabemontero** [comment]
> @Roming22 please provide the following in the commit message body (and pull request description):
> 
>     1. Which features are being promoted to production by this change?
> 
>     2. Why are we providing an overlay for performance settings?

@Roming22 @adambkaplan - I can help with 2) .... it will allow for direct manipulation of the performance settings for the new openshift CI based approach that @pmacik and @jhutar have discussed with me for vetting / confirming in an isolated fashion (i.e. not corrupted by other changes that may have merged into infra-deployments and the staging env) the effects of increasing the pipeline controller's work queue thread count, k8s client tuning.

The CI runs create create an infra-deployment branch with just that change, and they can measure the effects with more certainty.

Their prior attempt using staging was not conclusive because almost another 12 changes were introduced more or less concurrently after the summit freeze was lifted.

**Comment by Roming22** [comment]
@adambkaplan Commit message and description updated

**Review by adambkaplan — APPROVED** [review]

**Comment by adambkaplan** [comment]
I'll give CI one more pass - otherwise I approve a "red button" merge since these changes have been deployed and vetted in staging, and the changeset includes a security/threat-model related change.

**Pull request merged**
