### PR TITLE
Update release CRs in servicerelease tenant

### PR DESCRIPTION
**Pull request by scoheb**
- declare missing resources

### CODE REVIEW

**Comment by scoheb** [comment]
issue with getting the cluster kubeadmin during the tests

**Comment by scoheb** [comment]
[FAILED] [300.476 seconds][0m
[0m[spi-suite] [38;5;243mSVPI-395 - Github OAuth flow to upload token [38;5;9m[1m[It] SPITokenBinding should be in Injected phase[0m [38;5;204m[spi-suite, gh-oauth-flow][0m
[38;5;243m/tmp/tmp.GlR0LZzyP7/tests/spi/oauth.go:182[0m

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
