### PR TITLE
konflux(prod): move configuration from sandbox-sre

### PR DESCRIPTION
**Pull request by mfrancisc**
Jira: https://issues.redhat.com/browse/ASC-457

### CODE REVIEW

**Comment by mfrancisc** [comment]
waiting for https://github.com/redhat-appstudio/infra-deployments/pull/3229 to be merged

**Review by hugares — APPROVED** [review]

**Comment by hugares** [comment]
I did not add lgtm label as I have to leave in a few minutes, I prefer to be watch prod deployment to be sure there are no issue. Feel free to lgtm the change if you can keep an eye on it otherwise I will do it tomorrow

**Comment by sadlerap** [comment]
I think I'll leave it for the morning; in case something does go wrong, I'll have all day tomorrow to deal with it.

**Pull request merged**
