### PR TITLE
chore(RHTAPWATCH-365): Remove o11y dashboard deployment from infra-deployments

### PR DESCRIPTION
**Pull request by Kousalya1998**
* Remove the reference to o11y directory
* remove o11y subdirectory

### CODE REVIEW

**Review by hmariset — APPROVED** [review]
lgtm

**Comment by yftacherzog** [comment]
@Kousalya1998 Did you test it on a dev env to verify that everything is being deployed correctly and the change is as you expected?

**Comment by Kousalya1998** [comment]
@yftacherzog  I tested it on a dev env and everything is being deployed correctly. Now it's ready for review!!

**Review by amisstea — APPROVED** [review]

**Comment by amisstea** [comment]
/lgtm

@yftacherzog the e2e tests passed so I think this is safe to merge.

**Comment by hmariset** [comment]
> /lgtm
> 
> @yftacherzog the e2e tests passed so I think this is safe to merge.

Agree, Kousalya and I tested in the dev env and it worked as expected.

**Pull request merged**
