### PR TITLE
Clarify use of secrets in tekton-ci/konflux-ci

### PR DESCRIPTION
**Pull request by ralphbean**
There are two external secrets:

* One used to push to quay.io/redhat-appstudio in the tekton-ci namespace named `quay-push-secret`
* One used to push to quay.io/konflux-ci in the konflux-ci namespace named `quay-push-secret-konflux-ci`

This change should drop the konflux-ci secret from the tekton-ci namespace, and drop the tekton-ci secret from the konflux-ci namespace.

### CODE REVIEW

**Review by arewm — APPROVED** [review]

**Comment by gabemontero** [comment]
@ralphbean is there a Jira associated with this effort?

@jkhelil explains it to @enarha and myself, this is blocking his https://issues.redhat.com/browse/PLNSRVCE-1514 
and we'd like to specify the dependency.

thanks

**Comment by gabemontero** [comment]
> Yes, it is blocking @jkhelil's https://issues.redhat.com/browse/PLNSRVCE-1674

ok but your Jira @ralphbean is not listed as a blocker to https://issues.redhat.com/browse/PLNSRVCE-1674 when I view https://issues.redhat.com/browse/PLNSRVCE-1674 

I looked at the feature and think I found it .... https://issues.redhat.com/browse/KONFLUX-2098 

I'll update - thanks.

**Pull request merged**
