### PR TITLE
Revert Pipeline Service Update #1592

### PR DESCRIPTION
**Pull request by adambkaplan**
This reverts commit 8de070405118b3b984fa00aa06b2ff689923b075. This change has caused the Results apiserver to crashloop due to failed database automigrations.

Incident: https://issues.redhat.com/browse/PLNSRVCE-1262

### CODE REVIEW

**Comment by gabemontero** [comment]
I initiated https://redhat-internal.slack.com/archives/C02FANRBZQD/p1680625597334439 to ask about the e2e failure (which at a top level seems unrelated to placement service, but is application service / HAS related)

**Comment by adambkaplan** [comment]
/retest

Got bit by https://issues.redhat.com/browse/STONEBUGS-99

**Comment by gabemontero** [comment]
/retest

in case the private repo failure is a flake

**Comment by gabemontero** [comment]
> @adambkaplan I see a revert of EC that I'm not expecting based on the PR that is being reverted.

/hold

until @Roming22 's item here is addressed

**Comment by gabemontero** [comment]
e2e failed anyway

**Comment by gabemontero** [comment]
> /retest
> 
> Got bit by https://issues.redhat.com/browse/STONEBUGS-99

turns out https://issues.redhat.com/browse/DEVHAS-211 is the tracker for the app svcs fix

https://github.com/redhat-appstudio/e2e-tests/pull/425 disables the problematic test here

**Comment by Roming22** [comment]
/lgtm

The commit comes from rebasing the PR to main. The content and changeset ID are matching, so it's all good.
I'm not sure why it's showing as a diff though...

**Comment by gabemontero** [comment]
/hold

we may go with https://github.com/redhat-appstudio/infra-deployments/pull/1629 instead

**Comment by adambkaplan** [comment]
Unclear if these are flakes, or real error signals:

```
  [FAIL] [build-service-suite Build service E2E tests] HACBS pipelines [It] should validate Tekton Results [build, HACBS]
  [FAIL] [mvp-demo-suite MVP Demo tests] MVP Demo Chapter 2 - advanced pipeline, JVM rebuild, successful release [It] upgrading to SLSA level 3 customizable pipeline triggers creation of a PR in the sample repo [mvp-demo, mvp-demo-chapter-2]
```

Validate Tekton Results failure:
```
              Message: "Operation cannot be fulfilled on serviceaccounts \"tekton-results-tests\": the object has been modified; please apply your changes to the latest version and try again",

```

Customized pipeline failure:
```
  [FAILED] Timed out after 300.001s.
  timed out when waiting for init PaC PR to be created
  Expected
      <bool>: false
  to be true
  In [It] at: /tmp/tmp.yBD0GvQEst/tests/mvp-demo/mvp-demo.go:298 @ 04/04/23 19:30:45.6
```

**Comment by gabemontero** [comment]
the most recent e2e failure is PaC "related" according to the ginkgo description:

```
 • [FAILED] [300.697 seconds]
[mvp-demo-suite MVP Demo tests] MVP Demo Chapter 2 - advanced pipeline, JVM rebuild, successful release [It] upgrading to SLSA level 3 customizable pipeline triggers creation of a PR in the sample repo [mvp-demo, mvp-demo-chapter-2]
/tmp/tmp.yBD0GvQEst/tests/mvp-demo/mvp-demo.go:274
  [FAILED] Timed out after 300.001s.
  timed out when waiting for init PaC PR to be created
  Expected
      <bool>: false
  to be true
  In [It] at: /tmp/tmp.yBD0GvQEst/tests/mvp-demo/mvp-demo.go:298 @ 04/04/23 19:30:45.6 
```

is that related to the placement service "de-bump"?

I'll see what level of triage I can do before my EoB today.

**Comment by flacatus** [comment]
@adambkaplan we are using https://github.com/redhat-appstudio-qe/hacbs-test-project to test pac and we reach the limit of 20 webhooks there, i clean up the WHKs and now should be fine

**Comment by adambkaplan** [comment]
/close

#1629 won the race.

**Pull request closed without merging**
