### PR TITLE
PLNSRVCE-1674: Migrate SprayProxy images to quay.io/konflux-ci on stagging

### PR DESCRIPTION
**Pull request by jkhelil**
- Migrate the sprayproxy images to quay.io/konflux-ci/sprayproxy on  stagging

### CODE REVIEW

**Comment by enarha** [comment]
Do you know if the bot account was changed so it's able to push to that repo?

**Review by ramessesii2 — APPROVED** [review]
/lgtm

**Review by Roming22 — COMMENTED** [review]
/lgtm

**Review by Roming22 — APPROVED** [review]

**Comment by Roming22** [comment]
@jkhelil I've put the PR on hold as I do not see any images in https://quay.io/repository/konflux-ci/sprayproxy?tab=tags at the moment.

**Comment by gabemontero** [comment]
the f1afe07688592565986ded70ca912d80629c04a0 tag is now up at https://quay.io/repository/konflux-ci/sprayproxy?tab=tags

**Review by gabemontero — APPROVED** [review]
/lgtm

**Pull request merged**
