### PR TITLE
fix(STONEINTG-861): add 'Konflux Dev version' to CONSOLE_NAME

### PR DESCRIPTION
**Pull request by hongweiliu17**
* add Konflux Dev version to CONSOLE_NAME as default value (follow-up PR to address [this comment](https://github.com/redhat-appstudio/infra-deployments/pull/3763#discussion_r1611686741))

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Review by kasemAlem — APPROVED** [review]
/lgtm

**Comment by kasemAlem** [comment]
LGTM

**Review by dirgim — APPROVED** [review]
/lgtm
/approve

**Comment by kasemAlem** [comment]
issue with cluster deployment , retesting 

/test appstudio-e2e-tests

**Comment by MartinBasti** [comment]
Why this PR was closed?

**Comment by hongweiliu17** [comment]
I didn't close it... why it shows I closed?? Strange

**Comment by hongweiliu17** [comment]
Let me recreate a PR

**Comment by hongweiliu17** [comment]
https://github.com/redhat-appstudio/infra-deployments/pull/3807 is created.

**Pull request closed without merging**
