### PR TITLE
[OCP] Create new flavors with larger disk

### PR DESCRIPTION
**Pull request by ashwindasr**
Similar to https://github.com/redhat-appstudio/infra-deployments/pull/5050

### CODE REVIEW

**Review by hugares — APPROVED** [review]
/lgtm

**Comment by ashwindasr** [comment]
@hugares looks like we need a /ok-to-test as well?

**Comment by hugares** [comment]
> @hugares looks like we need a /ok-to-test as well?

you are right, I will blame late hour for missing this :)

**Comment by ashwindasr** [comment]
no worries - thanks as always Hugo!

**Comment by ashwindasr** [comment]
@hugares not sure why "Red Hat Konflux" is not running :thinking:

**Comment by hugares** [comment]
> @hugares not sure why "Red Hat Konflux" is not running 🤔

this is a known issue when someone outside of the org contribute a change. We will need to find out one day how to get this running but for now I will force merge

**Comment by ashwindasr** [comment]
Thanks @hugares. If it makes things easier, I can get myself added into the org.

**Comment by hugares** [comment]
> Thanks @hugares. If it makes things easier, I can get myself added into the org.

Invite sent :)

**Pull request merged**
