### PR TITLE
Remove pvc-cleaner

### PR DESCRIPTION
**Pull request by adambkaplan**
Remove the pvc-cleaner component from pipeline service. During kcp development, StoneSoup builds moved away from using a shared PVC to using VolumeClaimTemplates in their build pipelines. Cleanup of PVCs is accomplished when the associated PipelineRun object is pruned.

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Review by Michkov — CHANGES_REQUESTED** [review]
Also remove it from:
- components/tekton-ci/repository.yaml
- components/authentication/build.yaml

**Comment by Michkov** [comment]
@flacatus @psturc - @adambkaplan is attacking CI scripts, he is so immodest that he forked project to different name than origin - so instead infra-deployments it's in redhat-appstudio-infra-deployments

**Review by Michkov — APPROVED** [review]

**Comment by adambkaplan** [comment]
Filed https://github.com/redhat-appstudio/e2e-tests/issues/257

**Comment by Michkov** [comment]
@adambkaplan do you have any ticket for this issue? Who will delete service accounts created by pvc-cleaner?
```
$ oc get --no-headers -A sa | grep pvc-cleaner-pod-service-account | wc -l
94
```

**Comment by Michkov** [comment]
Tested in https://github.com/redhat-appstudio/infra-deployments/pull/1032

**Pull request merged**
