### PR TITLE
feat(STONEINTG-682): add base/overlay files for integration

### PR DESCRIPTION
**Pull request by hongweiliu17**
* add base/development/staging/production folder for integration
* update hack/preview.sh

Signed-off-by: Hongwei Liu <hongliu@redhat.com>

### CODE REVIEW

**Comment by MartinBasti** [comment]
@dirgim can give `/approve`, I cannot

**Review by dirgim — APPROVED** [review]
/lgtm
/approve

**Comment by hongweiliu17** [comment]
> I think we're also missing additions to [argo-cd-apps/overlays/development/kustomization.yaml](https://github.com/redhat-appstudio/infra-deployments/blob/main/argo-cd-apps/overlays/development/kustomization.yaml) and [argo-cd-apps/overlays/production/kustomization.yaml](https://github.com/redhat-appstudio/infra-deployments/blob/main/argo-cd-apps/overlays/production/kustomization.yaml).

Thanks! Updated

**Comment by hongweiliu17** [comment]
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/2765/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1725409435859292160 reports error `Error: error when bootstrapping cluster: reached maximum number of attempts (2). error: exit status 1`

**Review by dirgim — APPROVED** [review]
/lgtm

**Pull request merged**
