### PR TITLE
chore(STONEO11Y-86): create dev overlay for o11y

### PR DESCRIPTION
**Pull request by yftacherzog**
create dev overlay for o11y so that Prometheus rules will be deployed in dev and ci.

### CODE REVIEW

**Comment by yftacherzog** [comment]
@gbenhaim @amisstea @avi-biton @Omeramsc please take a look

**Review by Omeramsc — APPROVED** [review]
LGTM

**Review by amisstea — APPROVED** [review]

**Comment by gbenhaim** [comment]
all the tests passed except for one with a known issue https://issues.redhat.com/browse/HACBS-2061 and that is not related to this change.

**Pull request merged**
