### PR TITLE
chore(RHTAPWATCH-1164): onboard notification-controller to staging

### PR DESCRIPTION
**Pull request by avi-biton**

### CODE REVIEW

**Review by yftacherzog — COMMENTED** [review]
Maybe we can add a very basic README under `components/notification-controller`. Saying what this is about, and mentioning what to do if you want it deployed in dev.

This might be useful for us if we go back to this in few months time and try to recall how to make it work in dev.

**Review by gbenhaim — APPROVED** [review]

**Review by yftacherzog — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
