### PR TITLE
Authentication is very cluster specific, remove from devmode

### PR DESCRIPTION
**Pull request by sbose78**
Associated https://github.com/redhat-appstudio/infra-deployments/pull/86

### CODE REVIEW

**Review by jduimovich — APPROVED** [review]
LGTM

**Comment by jduimovich** [comment]
Added kustomize to remove the application from devmode.

**Comment by jduimovich** [comment]
This PR only affects the dev mode overlay so the current testing will not test this config. Merging

**Comment by sbose78** [comment]
Thank you!

**Pull request merged**
