### PR TITLE
Deploy backup component to host clusters

### PR DESCRIPTION
**Pull request by hugares**
For now, as per other cluster except stg-rh01, only create the application which contains only the external secrets to access the AWS bucket.

[RHTAPSRE-259](https://issues.redhat.com//browse/RHTAPSRE-259)

### CODE REVIEW

**Comment by dheerajodha** [comment]
(previously failed on [infra-related issue](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/2887/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1732935589298180096#1:build-log.txt%3A47))
/test appstudio-e2e-tests

**Comment by dheerajodha** [comment]
(same infra issue again)
/test appstudio-e2e-tests

**Comment by dheerajodha** [comment]
@hugares I don't have enough knowledge of the content of this PR, but do you think the infra-related failures in the CI job (`appstudio-e2e-tests`) could be due to it?

Because all of the [previous 6 CI runs](https://prow.ci.openshift.org/pr-history/?org=redhat-appstudio&repo=infra-deployments&pr=2887) of that job failed on setting up the infra.

**Comment by hugares** [comment]
> @hugares I don't have enough knowledge of the content of this PR, but do you think the infra-related failures in the CI job (`appstudio-e2e-tests`) could be due to it?
> 
> Because all of the [previous 6 CI runs](https://prow.ci.openshift.org/pr-history/?org=redhat-appstudio&repo=infra-deployments&pr=2887) of that job failed on setting up the infra.

Yeah, it looks like this change is breaking the deployment, I will look into it. Thanks for checking.

**Pull request merged**
