### PR TITLE
bump pipeline-service prod to current stage level

### PR DESCRIPTION
**Pull request by gabemontero**
Includes 
[Enable completed_run_grace_period for tekton-results](https://github.com/openshift-pipelines/pipeline-service/commit/b2626be4fc649b5184b8bf3e661bbc46319c884b)
[Fix TektonConfig](https://github.com/openshift-pipelines/pipeline-service/commit/db423b0030f4a0e886fdf7ce7f81e3c95e08d20e)
[Optimizing the process of ROSA provisioning in CI](https://github.com/openshift-pipelines/pipeline-service/commit/f74b260c32715977dcc7acc20a3b28e8cbac1454)
[Set Set cpu/memory requests/limits for tekton-results-api init contai…](https://github.com/openshift-pipelines/pipeline-service/commit/47c14a4acc7b99647ac7fabfef201af337725579)
[Set cpu/memory requests/limits for chains-secret-generation container](https://github.com/openshift-pipelines/pipeline-service/commit/7daba2740a9be1b2d8fc673a5dc7d35f57ba5b2c)
[Enable OSP pruner](https://github.com/openshift-pipelines/pipeline-service/commit/962f485476bb1c75a8f9f6a743a0cb953e587fbc)
[Update base images SHA in Dockerfiles](https://github.com/openshift-pipelines/pipeline-service/commit/ee4e0fea1244e47a6eaa92236d1b60957a33f1c6)
[update operator/gitops/argocd/pipeline-service/metrics-exporter/kusto…](https://github.com/openshift-pipelines/pipeline-service/commit/1f13ca5c4851190effa9660d55fbc20d459d7762)

/hold

a question if we need to clean up the terminated cron job affected by [Set cpu/memory requests/limits for chains-secret-generation container](https://github.com/openshift-pipelines/pipeline-service/commit/7daba2740a9be1b2d8fc673a5dc7d35f57ba5b2c)

### CODE REVIEW

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
per https://redhat-internal.slack.com/archives/C032EJ007C0/p1698255614479369 @Roming22 will handle any Job deletion needed to facilitate the gitops rollout in prod

**Comment by Roming22** [comment]
Force merging as the CI is failing but tis not impacted by the change.

**Comment by flacatus** [comment]
@Roming22 please report qe next time about failures and create RHTAP bug. If we don’t track ci bugs somewhere is hard for ys to provide fix to make ci pass in other jobs.

**Pull request merged**
