### PR TITLE
Update HAS to 45c4a52d9b6c567983ec72c3a6b776a95b99ba26

### PR DESCRIPTION
**Pull request by johnmcollier**
Pulls in:

- https://github.com/redhat-appstudio/application-service/pull/98
- https://github.com/redhat-appstudio/application-service/pull/99

### CODE REVIEW

**Review by elsony — APPROVED** [review]
/lgtm

**Comment by johnmcollier** [comment]
Looks like a flake. Maven central seems to be slow right now and it's causing the pipelinerun to reach the timeout in the tests

/retest

**Comment by johnmcollier** [comment]
Looks like the tests are broken?

Test failure also seen in 
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/305/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1519059246610649088 (#305)
- https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/297/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1518868259015757824

Retesting again just in case this is a stubborn flake

/retest

**Comment by sbose78** [comment]
Given this is unrelated and is needed to have the Gitops integration going, I will take this in.

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
