### PR TITLE
konflux(prod internal): registration service fix keycloak url

### PR DESCRIPTION
**Pull request by mfrancisc**
https://redhat-internal.slack.com/archives/C02CTEB3MMF/p1709282836087349

https://issues.redhat.com/browse/ASC-502

### CODE REVIEW

**Review by hugares — APPROVED** [review]

**Review by sadlerap — APPROVED** [review]

**Comment by hugares** [comment]
There are some failure in CI but this PR is not changing anything tested in CI. I am force merging this one

**Pull request merged**
