### PR TITLE
Test out building & deploying External Secrets

### PR DESCRIPTION
**Pull request by sbose78**
..using a Red Hat build.

* https://quay.io/repository/redhat-appstudio/external-secrets?tab=tags
* https://github.com/redhat-appstudio/external-secrets/tree/main/.tekton

image

Scans look pretty good.

https://issues.redhat.com/browse/RHTAP-905

### CODE REVIEW

**Review by ralphbean — APPROVED** [review]

**Comment by sbose78** [comment]
/test appstudio-hac-e2e-tests



<br class="Apple-interchange-newline">

**Comment by sbose78** [comment]
Closing this out, this will be moved into the application/component model.

**Comment by sbose78** [comment]
succeeded by https://github.com/redhat-appstudio/infra-deployments/pull/2061

**Pull request closed without merging**
