### PR TITLE
Complete SPI removal

### PR DESCRIPTION
**Pull request by mshaposhnik**
Complete removal of SPI and RemoteSecret entities

### CODE REVIEW

**Review by bamachrn — APPROVED** [review]
/lgtm

**Comment by jhutar** [comment]
Hello @mshaposhnik ! Is it possible this could have caused I can not run PromQL queries in OCP console -> Observe -> Metrics since yesterday or so? E.g. on stone-stage-p01 I'm getting: 
image

**Comment by mshaposhnik** [comment]
@jhhutar i don't think so, what makes you think that can be related to SPI ?

**Comment by jhutar** [comment]
Just the size of the PR I have not read through and I do not understand :) If it does not look possible, I'll keep looking. Thank you!

**Pull request merged**
