### PR TITLE
Update GitOps Service to latest

### PR DESCRIPTION
**Pull request by jgwest**

### CODE REVIEW

**Comment by Michkov** [comment]
Deployment appstudio-controller-controller-manager, SyncFailed
```
 "" is invalid: patch: Invalid value: "map[metadata:map[annotations:map[kubectl.kubernetes.io/last-applied-configuration:{\"apiVersion\":\"apps/v1\",\"kind\":\"Deployment\",\"metadata\":{\"annotations\":{},\"labels\":{\"app.kubernetes.io/instance\":\"gitops\",\"control-plane\":\"appstudio-controller-manager\"},\"name\":\"appstudio-controller-controller-manager\",\"namespace\":\"gitops\"},\"spec\":{\"replicas\":1,\"selector\":{\"matchLabels\":{\"control-plane\":\"appstudio-controller-manager\"}},\"template\":{\"metadata\":{\"annotations\":{\"kubectl.kubernetes.io/default-container\":\"manager\"},\"labels\":{\"control-plane\":\"appstudio-controller-manager\"}},\"spec\":{\"containers\":[{\"args\":[\"--secure-listen-address=0.0.0.0:8443\",\"--upstream=http://127.0.0.1:8080/\",\"--logtostderr=true\",\"--v=10\"],\"image\":\"gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0\",\"name\":\"kube-rbac-proxy\",\"ports\":[{\"containerPort\":8443,\"name\":\"https\",\"protocol\":\"TCP\"}]},{\"args\":[\"--health-probe-bind-address=:8085\",\"--metrics-bind-address=127.0.0.1:8080\",\"--leader-elect\",\"--zap-time-encoding=rfc3339nano\"],\"command\":[\"appstudio-controller\"],\"image\":\"quay.io/redhat-appstudio/gitops-service:c5da97e6b133295c4722ac678c5e8b05b0a714ce\",\"livenessProbe\":{\"httpGet\":{\"path\":\"/healthz\",\"port\":8085},\"initialDelaySeconds\":15,\"periodSeconds\":20},\"name\":\"manager\",\"readinessProbe\":{\"httpGet\":{\"path\":\"/readyz\",\"port\":8085},\"initialDelaySeconds\":15,\"periodSeconds\":10},\"resources\":{\"limits\":{\"cpu\":\"500m\",\"memory\":\"1024Mi\"},\"requests\":{\"cpu\":\"50m\",\"memory\":\"256i\"}},\"securityContext\":{\"allowPrivilegeEscalation\":false}}],\"securityContext\":{\"runAsNonRoot\":true},\"serviceAccountName\":\"appstudio-controller-controller-manager\",\"terminationGracePeriodSeconds\":10}}}}\n]] spec:map[template:map[spec:map[]]]]": unable to parse quantity's suffix
```

**Comment by Michkov** [comment]
https://github.com/redhat-appstudio/managed-gitops/pull/190

**Comment by jgwest** [comment]
Closing in favour of the other PR.

**Pull request closed without merging**
