### PR TITLE
Promote release-service from development to staging

### PR DESCRIPTION
**Pull request by seanconroy2021**
Included PRs:
 - https://github.com/konflux-ci/release-service/pull/497
 - https://github.com/konflux-ci/release-service/pull/496
 - https://github.com/konflux-ci/release-service/pull/495
 - https://github.com/konflux-ci/release-service/pull/493
 - https://github.com/konflux-ci/release-service/pull/492
 - https://github.com/konflux-ci/release-service/pull/491
 - https://github.com/konflux-ci/release-service/pull/489
 - https://github.com/konflux-ci/release-service/pull/490
 - https://github.com/konflux-ci/release-service/pull/488
 - https://github.com/konflux-ci/release-service/pull/487
 - https://github.com/konflux-ci/release-service/pull/486
 - https://github.com/konflux-ci/release-service/pull/483
 - https://github.com/konflux-ci/release-service/pull/482

### CODE REVIEW

**Review by theflockers — APPROVED** [review]
looks ok to me, but I'd like @johnbieren review just to make sure all these mod updates are expected to be here.

**Review by johnbieren — APPROVED** [review]
/lgtm

**Pull request merged**
