### PR TITLE
Reduce the Results buffer time to 1m in Development

### PR DESCRIPTION
**Pull request by khrm**
based on the conversation in [this thread](https://redhat-internal.slack.com/archives/C02M210JZ7B/p1732802281598569?thread_ts=1732713198.999119&cid=C02M210JZ7B)

### CODE REVIEW

**Review by psturc — APPROVED** [review]
/approve

**Review by enarha — COMMENTED** [review]
/lgtm

**Comment by psturc** [comment]
failed during bootstrap
```
Error from server (InternalError): error when applying patch:
{"metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"creationTimestamp\":null,\"name\":\"dora-metrics\"},\"spec\":{},\"status\":{}}\n"},"creationTimestamp":null,"labels":null}}
to:
Resource: "/v1, Resource=namespaces", GroupVersionKind: "/v1, Kind=Namespace"
Name: "dora-metrics", Namespace: ""
for: "STDIN": error when patching "STDIN": Internal error occurred: failed calling webhook "namespace.operator.tekton.dev": failed to call webhook: Post "[https://tekton-operator-proxy-webhook.openshift-pipelines.svc:443/namespace-validation?timeout=10s](https://tekton-operator-proxy-webhook.openshift-pipelines.svc/namespace-validation?timeout=10s)": no endpoints available for service "tekton-operator-proxy-webhook"
Error: error when bootstrapping cluster: reached maximum number of attempts (2). error: exit status 1
```
/retest-required

**Pull request merged**
