### PR TITLE
chore(STONEINTG-1013): increase Integration Pipeline timeout to 4hr+2hr

### PR DESCRIPTION
**Pull request by dheerajodha**

### CODE REVIEW

**Review by dirgim — APPROVED** [review]
/lgtm
/approve

**Review by jencull — APPROVED** [review]
lgtm

**Review by jencull — APPROVED** [review]
LGTM

**Comment by dheerajodha** [comment]
Tide is high on something right now.
The required test was passed and all required labels are present but still, it isn't auto-merging the PR.

**Pull request merged**
