### PR TITLE
bump pipeline-service prod to the same level that has been vetted in stage

### PR DESCRIPTION
**Pull request by gabemontero**
Includes these commits:
[Fix devenv image](https://github.com/openshift-pipelines/pipeline-service/commit/2a88f028fbd8521707964138a5576d9ecb619409)
[Fix upgrade-tests pipeline](https://github.com/openshift-pipelines/pipeline-service/commit/573268b9d5af7c8ebb00d389933a6bbe62f465af)
[remove references to chains ns](https://github.com/openshift-pipelines/pipeline-service/commit/a97b9b64e4e7f1f77a7693e3ed50cb56dd0e3f27)
[Update base images SHA in Dockerfiles](https://github.com/openshift-pipelines/pipeline-service/commit/8f1dd3276f4522405c9b9409748364f8e727615e)
[update operator/gitops/argocd/pipeline-service/metrics-exporter/kusto…](https://github.com/openshift-pipelines/pipeline-service/commit/0b7379e5c6b34e2ea8b319dc5bf4527bee687696)
[Add Sprayproxy Grafana panels](https://github.com/openshift-pipelines/pipeline-service/commit/57a38c32f9eccfea75b089d84e0f04c4653faf14)
[removed pull-secret](https://github.com/openshift-pipelines/pipeline-service/commit/03abba608ce18e736f06621ba0457c6352ff2b04)
[Update binaries](https://github.com/openshift-pipelines/pipeline-service/commit/ffbcbe234fb44be3f110c6f4dc9968edb51f4394)
[fix chains signing-secrets public-key access](https://github.com/openshift-pipelines/pipeline-service/commit/6dc09dfc80dc1d896dbe72a941b8ab6488d4c579)
[debug: remove commit](https://github.com/openshift-pipelines/pipeline-service/commit/a59ae0f231ad292b39960da700a7cd1885743723)
[Update binaries](https://github.com/openshift-pipelines/pipeline-service/commit/0316f4c3e52d77d6b70e95af482df606b4b9dca4)
[Make the tekton-chains signing-secrets immutable](https://github.com/openshift-pipelines/pipeline-service/commit/bcc955917b4fdafad8b7bc2122e33a779f8c6c56)
[Configure slack notification for plnsvc team when push task fails](https://github.com/openshift-pipelines/pipeline-service/commit/2df2218d148e4a7f6aa6f85808e7414bbde14910)
[Add errexit,nounset,pipefail to chains-secrets-config job](https://github.com/openshift-pipelines/pipeline-service/commit/4e8ed916b4d1c8d47da0da59ebabf852c5a5bebb)

### CODE REVIEW

**Comment by gabemontero** [comment]
/hold

https://github.com/redhat-appstudio/infra-deployments/pull/2412 needs to merge first

**Comment by gabemontero** [comment]
or we need to combine this with #2412 @ramessesii2 @Roming22

**Comment by gabemontero** [comment]
per https://redhat-internal.slack.com/archives/C032EJ007C0/p1695829839032639 I have combined this PR with #2412

**Review by Roming22 — APPROVED** [review]

**Comment by gabemontero** [comment]
still running its post test steps but e2e-tests passed:

```
Ran 366 of 481 Specs in 1421.688 seconds
SUCCESS! -- 366 Passed | 0 Failed | 11 Pending | 104 Skipped
```

**Comment by gabemontero** [comment]
various post merge checks reported in https://redhat-internal.slack.com/archives/C032EJ007C0/p1695829839032639 seem to indicate things are OK

also see various PaC pipelineruns triggered in the prd-rh tekton-ci namespace since the merge

**Pull request merged**
