### PR TITLE
   Upgrade Pipeline-Service

### PR DESCRIPTION
**Pull request by ramessesii2**
Upgrade Pipeline-Service
- change default SA for Pipelines to appstudio-pipeline    
- align tekton-results logs with [ADR-6](https://issues.redhat.com//browse/ADR-6)
#### Step 4 in the Rollout Plan for updating the default Service account in Pipelines.

### CODE REVIEW

**Comment by Michkov** [comment]
`failed to create task run pod "statusquarkusio-bmrm-dzxm5-build-container": pods "statusquarkusio-bmrm-dzxm5-build-container-pod" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider "pipelines-scc": Forbidden: not usable by user or serviceaccount, spec.containers[0].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added, spec.containers[2].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000910000, 1000919999], spec.containers[3].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000910000, 1000919999], spec.containers[4].securityContext.runAsUser: Invalid value: 0: must be in the ranges: [1000910000, 1000919999], spec.containers[4].securityContext.capabilities.add: Invalid value: "SETFCAP": capability may not be added, provider "restricted": Forbidden: not usable by user or serviceaccount, provider "nonroot-v2": Forbidden: not usable by user or serviceaccount, spec.containers[2].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden, spec.containers[3].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden, spec.containers[4].securityContext.runAsUser: Invalid value: 0: running with the root UID is forbidden, provider "hostmount-anyuid": Forbidden: not usable by user or serviceaccount, provider "hostnetwork-v2": Forbidden: not usable by user or serviceaccount, provider "hostnetwork": Forbidden: not usable by user or serviceaccount, provider "hostaccess": Forbidden: not usable by user or serviceaccount, provider "node-exporter": Forbidden: not usable by user or serviceaccount, provider "privileged": Forbidden: not usable by user or serviceaccount]. Maybe missing or invalid Task e2e-demos-nbwi-tenant/buildah` - Seems that pipelines-scc should be attached to the role.

**Comment by ramessesii2** [comment]
`appstudio-hac-e2e-tests` are failing with : 
```
+ echo 'Kubeadmin password file is empty... Aborting job'
Kubeadmin password file is empty... Aborting job
+ exit 1
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"k8s.io/test-infra/prow/entrypoint/run.go:79","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2023-05-15T10:46:30Z"}
error: failed to execute wrapped command: exit status 1
```

**Review by Roming22 — APPROVED** [review]

**Pull request merged**
