### PR TITLE
feat(hack): add support for dev mode with 'git@' remotes

### PR DESCRIPTION
**Pull request by goldmann**

### CODE REVIEW

**Comment by goldmann** [comment]
FYI @Michkov

**Comment by Michkov** [comment]
Personally I am pointing `origin` to main repo (not fork). Forks are other remotes. 

Rather use sed instead of bashisms -> `MY_GIT_REPO_URL=$(git config --get remote.origin.url | sed 's|^git@github.com:|https://github.com/|')`

**Comment by goldmann** [comment]
Indeed, `sed` is cleaner, I'll get this updated.

**Comment by goldmann** [comment]
@Michkov Done!

**Comment by goldmann** [comment]
Regarding remote names - I guess this bit is fragile here. We probably should switch to `git ls-remote --get-url`.

**Comment by goldmann** [comment]
Aaaaand - done!

**Comment by Michkov** [comment]
wow, now it's uber cool

**Review by sbose78 — APPROVED** [review]

**Pull request merged**
