### PR TITLE
PLNSRVCE-1310: reenable in dev/stage, but keeping disable patch around for now, pipeline service metrics exporter

### PR DESCRIPTION
**Pull request by gabemontero**

### CODE REVIEW

**Comment by gabemontero** [comment]
1 unrelated SPI flake, and the exporter is up an running per https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1933/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1667266335282827264/artifacts/appstudio-e2e-tests/redhat-appstudio-hypershift-gather/artifacts/pods/openshift-pipelines_pipeline-metrics-exporter-6bb8cf94-js2rh_pipeline-metrics-exporter.log 

I'll wait until @Roming22 gives a review and then if need be will hit the merge button so we can start monitoring the exporter in staging

**Comment by Roming22** [comment]
@gabemontero I’m travelling so I won’t be very responsive. I’m okay with merging the PR if the tests results are good enough.

**Review by Roming22 — APPROVED** [review]

**Comment by flacatus** [comment]
/test appstudio-e2e-tests
CI flakiness..

**Comment by flacatus** [comment]
/test appstudio-e2e-tests
CI flakiness..

**Pull request merged**
