### PR TITLE
do not merge: test redhat-appstudio/e2e-tests/pull/176

### PR DESCRIPTION
**Pull request by psturc**
FYI @gabemontero 

this is the PR for testing https://github.com/redhat-appstudio/e2e-tests/pull/176 to raise our confidence about the changes introduced in that PR

### CODE REVIEW

**Comment by psturc** [comment]
connection issue
/retest

**Comment by psturc** [comment]
@gabemontero pairing of this PR with e2e-tests PR worked:
```
[INFO] Cloning tests from branch PLNSRVCE-533 repository https://github.com/psturc/e2e-tests.git
Cloning into '/go/src/github.com/redhat-appstudio/infra-deployments/tmp/e2e-tests'...
```
(got this from a [CI build log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/628/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1559899804975239168/artifacts/appstudio-e2e-deployment/appstudio-e2e-deployment/build-log.txt))

and e2e is green.

**Comment by gabemontero** [comment]
> @gabemontero pairing of this PR with e2e-tests PR worked:
> 
> ```
> [INFO] Cloning tests from branch PLNSRVCE-533 repository https://github.com/psturc/e2e-tests.git
> Cloning into '/go/src/github.com/redhat-appstudio/infra-deployments/tmp/e2e-tests'...
> ```
> 
> (got this from a [CI build log](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/628/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1559899804975239168/artifacts/appstudio-e2e-deployment/appstudio-e2e-deployment/build-log.txt))
> 
> and e2e is green.

perfect - thanks @psturc 

per stand up, let's re test a few times to make sure we just did not get lucky

/test appstudio-e2e-deployment

**Comment by gabemontero** [comment]
another green run - try # 3

```
[38;5;243m------------------------------[0m
[38;5;10m• [SLOW TEST] [408.787 seconds][0m
[0m[jvm-build-service-suite JVM Build Service E2E tests] [38;5;243mwhen the Component with s2i-java component is created [0msome artifactbuilds and dependencybuilds complete[0m [38;5;204m[jvm-build][0m
[38;5;243m/go/src/github.com/redhat-appstudio/infra-deployments/tmp/e2e-tests/tests/build/jvm-build.go:249[0m
```

/test appstudio-e2e-deployment

**Comment by gabemontero** [comment]
appstudio bootstrap fail

run # 4

/test appstudio-e2e-deployment

**Comment by gabemontero** [comment]
green again ... 4th success

```
[38;5;243m------------------------------[0m
[38;5;10m• [SLOW TEST] [358.219 seconds][0m
[0m[jvm-build-service-suite JVM Build Service E2E tests] [38;5;243mwhen the Component with s2i-java component is created [0msome artifactbuilds and dependencybuilds complete[0m [38;5;204m[jvm-build][0m
[38;5;243m/go/src/github.com/redhat-appstudio/infra-deployments/tmp/e2e-tests/tests/build/jvm-build.go:249[0m
[38;5;243m------------------------------[0m
```
going for 5

/test appstudio-e2e-deployment

**Comment by gabemontero** [comment]
green again

/test appstudio-e2e-deployment

**Comment by gabemontero** [comment]
@psturc I'm going to go ahead and 

/lgtm

but also 

/hold

if you want to update this PR per our video conf today, I'll have to re lgtm anyway.  However, if it makes sense to merge this PR and then follow up with the "validate test repo changes" scenario, I'm good with that as well, and you can cancel the hold when you come in the morning and merge.

I submitted one more test, but this thing is looking green.

**Comment by gabemontero** [comment]
oops / wrong PR

/lgtm cancel

**Comment by gabemontero** [comment]
same success as before @psturc 

this time I even looked at the test namespace artifact cache and saw entries I would expect after building the test app

**Pull request closed without merging**
