### PR TITLE
Disabling staging promotion pipeline run and repository

### PR DESCRIPTION
**Pull request by prietyc123**
We are facing issue quite often that the staging test get triggered even it is disabled due to [bug in pac](https://issues.redhat.com/browse/SRVKP-4018) . So I have moved the file from .tekton directory

rh-pre-commit.version: 2.1.0
rh-pre-commit.check-secrets: ENABLED

@Roming22 @hugares @tisutisu

### CODE REVIEW

**Review by hugares — APPROVED** [review]

**Comment by Roming22** [comment]
@prietyc123 Please remove the resources from the repo instead of just commenting them out or moving them out of the way.

Make sure that you document the PR/changeset of your original change in the Epic/Feature so that it can easily be retrieved in the future if needed.

**Comment by hugares** [comment]
/hold

Preventing merge to allow to address @Roming22's comment

**Comment by prietyc123** [comment]
> @prietyc123 Please remove the resources from the repo instead of just commenting them out or moving them out of the way.

@Roming22 Are you suggesting to remove whole promotion component itself?

**Comment by prietyc123** [comment]
@hugares @Roming22 Its ready now

**Review by Roming22 — APPROVED** [review]
/lgtm

**Comment by Roming22** [comment]
@prietyc123 CI failing because of the current issue with Tekton Results, you'll need to retrigger the tests once it is solved.

**Pull request merged**
