### PR TITLE
Fix deployment of kubesaw-common application

### PR DESCRIPTION
**Pull request by hugares**
The deployment was failing due to the missing namespace. Create the namespace resource and also add the namespace directive in the kustomization file to create all resources in the namespace.

[ASC-503](https://issues.redhat.com//browse/ASC-503)

### CODE REVIEW

**Review by dperaza4dustbit — COMMENTED** [review]
This looks good to me, just one comment before approve should we set this to false on the kubesaw-common application:

syncOptions:
          - CreateNamespace=true

**Comment by hugares** [comment]
> This looks good to me, just one comment before approve should we set this to false on the kubesaw-common application:
> 
> syncOptions: - CreateNamespace=true

Good point, done in latest revision

**Review by dperaza4dustbit — APPROVED** [review]
/lgtm

**Pull request merged**
