### PR TITLE
fix: add missing files in application-api application

### PR DESCRIPTION
**Pull request by rhopp**
Signed-off-by: Radim Hopp <rhopp@redhat.com>

### CODE REVIEW

**Review by johnmcollier — APPROVED** [review]

**Review by flacatus — APPROVED** [review]

**Comment by rhopp** [comment]
I'm force-merging this one to unblock us from this deadlock. This should unblock (or at least keep us moving forward in) https://github.com/openshift/release/pull/34064

**Comment by MatousJobanek** [comment]
@jgwest @Michkov  do we really need these additional (Cluster)Role(Bindings) defined here? I thought that ArgoCD should have cluster-admin permissions. :man_shrugging: 

In addition, I see that the same set of RBAC is defined per component - having these ClusterRole(Binding)s per component doesn't make any sense because:
* it's cluster-scoped
* they are not limited to the particular `customresourcedefinitions` resource names.

But still - why ArgoCD needs them at all?

**Comment by Michkov** [comment]
@sbose78 could you answer @MatousJobanek question?

**Comment by Michkov** [comment]
@sbose78 Answer:
```
This was needed to ensure Argo CD has permissions to CRUD in the namespace.
... after we remove cluster-admin privlieges from the ArgoCD
```

**Pull request merged**
