### PR TITLE
Added token expiration duration to readme

### PR DESCRIPTION
**Pull request by bamachrn**
This PR updates the token duration for grafana datasource authentications

Signed-off-by: Bama Charan Kundu <bamachrn@gmail.com>

### CODE REVIEW

**Review by xcoulon — APPROVED** [review]

**Comment by amfred** [comment]
Setting a long expiration time on a token is a useful hack, but I don't want to recommend it.  We really need to figure out how to automatically rotate it correctly.

**Comment by Omeramsc** [comment]
> Setting a long expiration time on a token is a useful hack, but I don't want to recommend it. We really need to figure out how to automatically rotate it correctly.

Can [this](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token) be a possible solution?  or using an operator/sidecar container to renew the token

**Comment by xcoulon** [comment]
> > Setting a long expiration time on a token is a useful hack, but I don't want to recommend it. We really need to figure out how to automatically rotate it correctly.
> 
> Can [this](https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#create-token) be a possible solution? or using an operator/sidecar container to renew the token

this looks interesting, indeed!

**Pull request merged**
