### PR TITLE
Disable rekor integration

### PR DESCRIPTION
**Pull request by lcarva**
This aligns with the current plan to not have Rekor enabled initially, but introduce it post-mvp phase.

Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by lcarva** [comment]
@redhat-appstudio/enterprise-contract ptal

**Comment by zregvart** [comment]
I guess e2e tests need an update first...

```
[INFO] Cloning tests from branch pre-kcp repository https://github.com/redhat-appstudio/e2e-tests.git
Cloning into '/go/src/github.com/redhat-appstudio/infra-deployments/tmp/e2e-tests'...
fatal: Remote branch pre-kcp not found in upstream origin
Unexpected end of command stream
[ERROR] Job failed with code 128. 
```

**Review by simonbaird — APPROVED** [review]

**Comment by lcarva** [comment]
e2e test failures seem to be unrelated.

**Comment by Michkov** [comment]
So https://github.com/redhat-appstudio/infra-deployments/blob/main/hack/preview.sh#L78-L80 should be removed as well?

**Comment by lcarva** [comment]
> So https://github.com/redhat-appstudio/infra-deployments/blob/main/hack/preview.sh#L78-L80 should be removed as well?

I'd rather not as part of this PR. Rekor is something we still want, just not right now. There's still value in setting `transparency.url` because it allows us to simply toggle `transparency.enabled` to use Rekor which is helpful in a dev environment.

There's more work that needs to be done around Rekor. This PR is the bare minimum needed right now.

**Comment by lcarva** [comment]
/lgtm

(re-adding label after rebase)

**Pull request merged**
