### PR TITLE
PLNSRVCE-1318: scale down pipeline-metrics-exporter until we fix scaling/perf issues

### PR DESCRIPTION
**Pull request by gabemontero**
See https://redhat-internal.slack.com/archives/C02FTKEMBU1/p1684350155144749

/assign @adambkaplan 
/assign @Roming22

### CODE REVIEW

**Review by adambkaplan — APPROVED** [review]
/approve

Non-blocking nit - I _think_ we can use regular YAML to do a strategic merge patch, rather than use jsonpatch-style changes.

**Comment by adambkaplan** [comment]
Given we are in code freeze, we should:

1. Have a JIRA issue to track this, and get PM and Engineering approvals
2. Have someone another +1 - perhaps @amfred

**Comment by gabemontero** [comment]
> Given we are in code freeze, we should:
> 
>     1. Have a JIRA issue to track this, and get PM and Engineering approvals
> 
>     2. Have someone another +1 - perhaps @amfred

Jira opened and associated with this PR.

@sbose78 - is the process that our architect solicits the PM etc. approval, like you did with the recent sprayproxy item?

**Comment by gabemontero** [comment]
All that said, I still see an exporter pod in the artifacts:  https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1826/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1658927029027868672/artifacts/appstudio-e2e-tests/redhat-appstudio-hypershift-gather/artifacts/pods/openshift-pipelines_pipeline-metrics-exporter-7f7b94549b-2fldh_pipeline-metrics-exporter.log

I'll confirm with a local test tomorrow, switch to strategic merge patch approach if need be per https://github.com/redhat-appstudio/infra-deployments/pull/1826#pullrequestreview-1431571237 while approvals are sorted out

**Comment by sbose78** [comment]
@gabemontero Yes, either that, or a slack post.

**Review by adambkaplan — APPROVED** [review]
/lgtm

Will lift the hold with product and engineering approvals.

**Comment by gabemontero** [comment]
confirmed no metrics exporter pods in https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/1826/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-tests/1659264729928962048/artifacts/appstudio-e2e-tests/redhat-appstudio-hypershift-gather/artifacts/pods/

**Pull request merged**
