### PR TITLE
feat: Added more graphs to perf dashboard and organized it to rows

### PR DESCRIPTION
**Pull request by jhutar**

### CODE REVIEW

**Comment by dheerajodha** [comment]
Test failed on [RHTAPBUGS-985](https://issues.redhat.com/browse/RHTAPBUGS-985?focusedId=23524240&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23524240). It's a known bug, and we're looking into it.

/test appstudio-e2e-tests

**Review by avi-biton — APPROVED** [review]
/lgtm
/approve

**Comment by jhutar** [comment]
Thank you all!

**Pull request merged**
