### PR TITLE
Fix timeout for remote-secret-controller-in-cluster-local

### PR DESCRIPTION
**Pull request by Katka92**
The application was not created during the given timeout which failed the script. Increasing the timeout should solve the problem.
Related issue: [HAC-4343](https://issues.redhat.com/browse/HAC-4343)

### CODE REVIEW

**Comment by Katka92** [comment]
@albarbaro @rsoaresd Hello, I hope I've pinged the right people :sweat_smile: Could you please look at those changes? :slightly_smiling_face: Thanks

**Review by albarbaro — APPROVED** [review]

**Pull request merged**
