### PR TITLE
feat(ASC-262): multi cluster deployment

### PR DESCRIPTION
**Pull request by gbenhaim**
This change introduce the ability to deploy StoneSoup into multiple
clusters. The general guideline is to reduce as much as possible
the scripts that are needed for deployment, and rely on ArgoCD instead.

The change can be split into 4 topics:

ArgoCD:

Instead of using Applications, use ApplicationSets with the cluster
generator the is configured with label selectors (using Kustomize).

Compose the different ApplicationSets in directories that reflect the
role of the cluster in the fleet (e.g host, member).

Hack Directory:

Move the logic that responsible for creating secrets into dedicated
scripts.

Create bootstrap scripts for the different cluster types.

Adjust preview.sh to work with the new ArgoCD manifests.

Move the ArgoCD deployment to dedicated script.

Note - This change preserves the ability to install StoneSoup into a
single cluster for development purposes.

Components Directory:

The Gitops service requires that the openshift-gitops operator will be
installed in the cluster. Deploy the subscription as part of the
deployment of the Gitops service.

The ArgoCD operator version was upgraded to 1.7 since it contained
a fix to a bug affected the deployment of multiple clusters
[GITOPS-2015](https://issues.redhat.com//browse/GITOPS-2015)

Docs:

Update the docs according to the changes. The multi cluster docs
are still not complete. Those can be completed when we sort out
the injection of secrets to the clusters.

Out of scope:

- Vault deployment in member clusters
- Injecting the required secrets for the StoneSoup components
  from a central location.

Signed-off-by: gbenhaim <gbenhaim@redhat.com>

### CODE REVIEW

**Review by Michkov — APPROVED** [review]

**Comment by gbenhaim** [comment]
I'm going to use the `multi-cluster` branch for deploying the new staging instance. Once it's functional, we can proceed with this PR.

**Comment by Michkov** [comment]
`"Pipeline build-e2e-ppav/test-component-pac-uabl-on-pull-request-79xp9 can't be Run; it contains Tasks that don't exist: Couldn't retrieve Task \"sanity-inspect-image\": Get \"https://quay.io/v2/redhat-appstudio-tekton-catalog/task-sanity-inspect-image/manifests/sha256:1ff8cea8259a415a7ca6de7d47ade692813721653f89166f549e732cecaf2dcf\": context deadline exceeded"` - SRVKP-2749

/test appstudio-e2e-tests

**Pull request merged**
