### PR TITLE
Allow testing with repo url that ends with .git

### PR DESCRIPTION
**Pull request by tkdchen**
Signed-off-by: Chenxiong Qi <cqi@redhat.com>

I have been using this snippet for my testing for PLNSRVCE-693. Hopefully, it is useful for others as well.

### CODE REVIEW

**Comment by gbenhaim** [comment]
shouldn't the component the uses the repo url know how to handle a url that ends with `.git`?

**Comment by Michkov** [comment]
Agree with @gbenhaim this is about hiding, I prefer to not do this.

**Comment by Michkov** [comment]
@tkdchen so now I can see what this is doing, it's just fixes component name, it's not touching repository. So please reopen.

**Pull request merged**
