### PR TITLE
Allow toggle ArgoCD sync for enterprise-contract and rekor

### PR DESCRIPTION
**Pull request by lcarva**
Signed-off-by: Luiz Carvalho <lucarval@redhat.com>

### CODE REVIEW

**Comment by lcarva** [comment]
@redhat-appstudio/enterprise-contract ptal

**Comment by zregvart** [comment]
Also #434 is of note here. The change in here will require a change in the [Tekton pipeline](https://github.com/hacbs-contract/enterprise-contract-controller/blob/1336dcc40553ef59eda9b681ec96b0b18c06f0dd/.tekton/push.yaml#L19)

**Comment by lcarva** [comment]
> Also #434 is of note here. The change in here will require a change in the [Tekton pipeline](https://github.com/hacbs-contract/enterprise-contract-controller/blob/1336dcc40553ef59eda9b681ec96b0b18c06f0dd/.tekton/push.yaml#L19)

I think this comment was meant to be written in https://github.com/redhat-appstudio/infra-deployments/pull/430.

**Comment by zregvart** [comment]
I can't find PipelineRun objects in the must-gather, but based on the [chains-controller logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/redhat-appstudio_infra-deployments/431/pull-ci-redhat-appstudio-infra-deployments-main-appstudio-e2e-deployment/1534851491322400768/artifacts/appstudio-e2e-deployment/gather-extra/artifacts/pods/tekton-chains_tekton-chains-controller-5fbcff57b9-f8txm_tekton-chains-controller.log) the PipelineRun which we expect to finish [within 180 seconds](https://github.com/redhat-appstudio/e2e-tests/blob/main/tests/build/chains.go#L61) finishes in 201 seconds (2022-06-09T11:11:46.161Z till 2022-06-09T11:15:07.612Z)

**Pull request merged**
